# Typed lowered IR -> C source, one concrete MethodInstance at a time.
#
# Walks the *unoptimized* typed CodeInfo (`code_typed(optimize=false)`): every value
# carries its inferred concrete type, local variable names survive, and arithmetic
# appears as calls to +, -, *, / rather than intrinsics. Julia locals become C locals
# named by the rules in `name.jl`; intermediate values become temps named by the rules
# on `temp!`. Operations on arrays become calls to helpers generated by `helper.jl`;
# control flow is recovered from gotos by `flow.jl`.

include("name.jl")
include("type.jl")
include("prose.jl")
include("helper.jl")
include("source.jl")

# Per-function state.
mutable struct Scope
    ci::Core.CodeInfo
    names::Vector{String}               # C name of each slot (index 1 is `#self#`, unused)
    result::String                      # name for an unnamed result, `result` unless that's taken
    resultname::String                  # the same, kept after `result` is claimed
    resultparam::Bool                   # the result is an array, passed out through a parameter
    staticarray::Bool                   # every array is fixed-size; dynamic operations are errors
    limit::Int                          # longest temp name we're willing to mangle to
    blocked::Set{Int}                   # temp numbers already taken by the user's own names
    counter::Int
    expr::Dict{Int, String}             # SSA id -> the C expression that stands for it
    helpers::Dict{String, String}       # shared across the whole output; see helper.jl
    headers::Set{String}                # shared: standard headers the output needs
    # Sizes the IR doesn't know: a regular array's type has none, so the transpiler
    # tracks a shaped stand-in for each SSA value and slot that holds one.
    shapes::Dict{Int, Type}             # SSA id -> shaped type
    slotshapes::Dict{Int, Type}         # slot id -> shaped type
    rettype::Type                       # the (shaped) type actually returned
    # Source annotations (see source.jl): the file, each statement's line, how far
    # into the file the comments have been emitted, and whether code lines are copied.
    src::Union{Source, Nothing}
    stmtline::Vector{Int}
    cursor::Int
    copycode::Bool
    # Control flow (see flow.jl).
    depth::Int                          # current nesting, for indentation
    inlined::Set{Int}                   # SSA ids rendered inside conditions, not as temps
    skipped::Set{Int}                   # statements consumed by a construct; never emitted
    hidden::Set{Int}                    # slots never declared: iterator state, loop variables, aliases
    mutated::Set{Int}                   # array slots written through setindex!
    loops::Vector{Tuple{Int, Int}}      # enclosing loops: (break target, continue target)
    fors::Dict{Int, Any}
    whiles::Dict{Int, Any}
end

function Scope(ci::Core.CodeInfo, mi::Core.MethodInstance, sig, limit::Integer, staticarray::Bool, helpers, headers, copycode::Bool, blocked)
    names = ["#self#"; identifiers([isempty(string(s)) ? "#s$i" : string(s) for (i, s) in enumerate(ci.slotnames[2:end])]; blocked)]
    hidden = Set{Int}(i for (i, s) in enumerate(ci.slotnames) if i > 1 && isempty(string(s)))
    result = "result"
    while result in names
        result *= "_"
    end
    blocked = Set{Int}()
    for s in names
        m = match(r"^temp(\d+)(_.*)?$", s)
        m === nothing || push!(blocked, parse(Int, m[1]))
    end
    slotshapes = Dict{Int, Type}(i + 1 => T for (i, T) in enumerate(sig) if isarray(T))
    src = Source(mi.def)
    stmtline = src === nothing ? zeros(Int, length(ci.code)) : statementlines(mi, length(ci.code))
    return Scope(ci, names, result, result, false, staticarray, limit, blocked, 0, Dict{Int, String}(), helpers, headers,
                 Dict{Int, Type}(), slotshapes, Union{}, src, stmtline, src === nothing ? 0 : src.first - 1, copycode,
                 0, Set{Int}(), Set{Int}(), hidden, Set{Int}(), Tuple{Int, Int}[], Dict{Int, Any}(), Dict{Int, Any}())
end

include("flow.jl")

"""
    cfunction(name, mi, sig, helpers, headers; templimit=40, staticarray=true, source=true) -> (prototype, definition)

C source for the concrete MethodInstance `mi`, named `name` in C, with argument types
`sig` — the instance's own types, except that a regular array is given as a shaped
stand-in carrying the size the IR doesn't know. Any array helpers it needs are added
to `helpers`, and any standard headers to `headers`.
"""
function cfunction(name::AbstractString, mi::Core.MethodInstance, sig, helpers::Dict{String, String}, headers::Set{String};
                   templimit::Integer=40, staticarray::Bool=true, source::Bool=true, blocked=())
    ci, rettype = only(Base.code_typed_by_type(mi.specTypes; optimize=false))
    sc = Scope(ci, mi, sig, templimit, staticarray, helpers, headers, source, blocked)
    sc.resultparam = isarray(rettype)
    sc.rettype = widen(rettype)
    if sc.resultparam
        # An array comes out through a parameter, and an output parameter is `out` —
        # `result` is kept for a returned scalar (see naming.md).
        sc.result = sc.resultname = free("out", sc.names)
    end
    analyze!(sc)

    body = String[]
    block!(body, sc, 1, length(ci.code))
    sc.src === nothing || annotate!(body, sc, sc.src.last)   # whatever follows the last statement

    # Declarations come after the walk: a regular array's size is only known once
    # something has been stored in it.
    lines = [declare(slottype(sc, i), sc.names[i]) * ";" for i in ci.nargs+1:length(ci.slotnames) if !(i in sc.hidden)]
    append!(lines, body)

    params = [declare(slottype(sc, i), sc.names[i]; constant=isarray(slottype(sc, i)) && !(i in sc.mutated)) for i in 2:ci.nargs]
    if sc.resultparam
        # C can't return an array; it comes out through a trailing parameter, which
        # takes the result's name.
        push!(params, declare(sc.rettype, sc.resultname))
        signature = "void $name($(join(params, ", ")))"
    else
        signature = "$(ctype(rettype)) $name($(isempty(params) ? "void" : join(params, ", ")))"
    end
    comments, doc = sc.src === nothing ? (String[], String[]) : leading(sc.src)
    origin = "$(mi.def.name)($(join(("$(ci.slotnames[i])::$(widen(ci.slottypes[i]))" for i in 2:ci.nargs), ", ")))" *
             (sc.src === nothing ? "" : ", $(sc.src.name):$(sc.src.first)")
    block = doxygen(doc, origin, sc.names[2:ci.nargs], sc.resultparam ? sc.resultname : nothing)
    return signature * ";", join([comments; block; signature * " {"; "    " .* lines; "}"], "\n") * "\n", sc.names
end

# Everything that has to be known before emission starts: the loops, the statements
# they consume, the values rendered inline, mutated parameters, and slots that are
# only copies of another slot with the same name (a loop variable re-bound for an
# inner loop) — those take the original's name and vanish.
function analyze!(sc::Scope)
    ci = sc.ci
    code = ci.code
    sc.fors = findfors(ci)
    for F in values(sc.fors)
        push!(sc.hidden, F.var)
        for i in F.start:F.bodylo-1; push!(sc.skipped, i); end
        for i in F.next:F.exit-1;    push!(sc.skipped, i); end
        for i in F.machinery;        push!(sc.skipped, i); end
    end
    sc.whiles = findwhiles(ci, sc.fors)
    markinlined!(sc, sc.fors)
    # Statements consumed by the one that uses them: the pieces of a broadcast, and
    # the tuples that group constructor arguments.
    for (i, st) in enumerate(code)
        st isa Expr && st.head === :call || continue
        f = callee_or_nothing(ci, st.args[1])
        (f === Base.broadcasted || f === Core.tuple) && push!(sc.skipped, i)
    end
    for st in code
        st isa Expr && st.head === :call && callee_or_nothing(ci, st.args[1]) === Base.setindex! &&
            st.args[2] isa Core.SlotNumber && push!(sc.mutated, st.args[2].id)
    end
    assigned = Dict{Int, Vector{Int}}()
    for (i, st) in enumerate(code)
        st isa Expr && st.head === :(=) && push!(get!(assigned, st.args[1].id, Int[]), i)
    end
    for (s, at) in assigned
        length(at) == 1 || continue
        rhs = code[at[1]].args[2]
        rhs isa Core.SSAValue && code[rhs.id] isa Core.SlotNumber || continue
        t = code[rhs.id].id
        ci.slotnames[s] == ci.slotnames[t] || continue
        sc.names[s] = sc.names[t]
        push!(sc.hidden, s)
        push!(sc.skipped, at[1])
    end
end

callee_or_nothing(ci, x) = try callee(ci, x) catch; nothing end

# Append a line at the current nesting depth.
emit!(lines, sc::Scope, s::AbstractString) = push!(lines, "    "^sc.depth * s)

# Carry the source's comments (and, if asked, code) forward through line `line`, so
# they sit just ahead of the C for the statement on that line.
function annotate!(lines, sc::Scope, line)
    sc.src === nothing && return
    line > sc.cursor || return
    for l in body(sc.src, sc.cursor + 1, line; code=sc.copycode)
        emit!(lines, sc, l)
    end
    sc.cursor = line
end

# The type of a slot, shaped if it holds an array.
slottype(sc::Scope, i) = get(sc.slotshapes, i, widen(sc.ci.slottypes[i]))

# Emit the C for one IR statement, appending to `lines`.
function statement!(lines, sc::Scope, i, st)
    ci = sc.ci
    st === nothing && return
    st isa GlobalRef && return                    # constant load; resolved where it's used
    st isa Core.NewvarNode && return
    st isa Expr && st.head in (:meta, :code_coverage_effect) && return
    i in sc.inlined && return                     # rendered inside a condition
    T = widen(ci.ssavaluetypes[i])
    T === Union{} && return                       # unreachable
    if st isa Core.ReturnNode
        v = value(sc, st.val)
        if sc.resultparam
            # An array result is written into the out parameter; if it isn't there
            # already, copy it. The result has Julia's return type where that has a
            # size, otherwise the value's own; a transposed value landing in a plain
            # type is copied with its axes swapped. A `return` is only needed before
            # the end.
            shape(sc.rettype) === nothing && (sc.rettype = valuetype(sc, st.val))
            v == sc.resultname || emit!(lines, sc, "$(copyhelper(sc, st.val, sc.rettype))($v, $(sc.resultname));")
            i == length(ci.code) || emit!(lines, sc, "return;")
        else
            emit!(lines, sc, "return $v;")
        end
    elseif st isa Expr && st.head === :call
        f = callee_or_nothing(ci, st.args[1])
        if f === Base.setindex!
            emit!(lines, sc, "$(index(sc, st.args[2], st.args[4:end])) = $(value(sc, st.args[3]));")
        elseif f in (Base.zeros, Base.ones, Base.fill) || (f in (Base.zero, Base.one) && isarray(T)) || isconstruction(f) || f === Base.materialize
            dest = onlyreturned(ci, i) ? result!(sc, i) : temp!(sc, i, parts(sc, st))
            construct!(lines, sc, i, st, dest; declaration=!(onlyreturned(ci, i) && sc.resultparam))
        elseif (f === Base.adjoint || f === Base.transpose) && isarray(T)
            # A transpose is the same storage with its axes read the other way round:
            # nothing to do in C, the value just carries the tag from here on.
            sc.expr[i] = value(sc, st.args[2])
            sc.shapes[i] = transposed(valuetype(sc, st.args[2]))
        elseif f === Colon() || f === Base.OneTo || f === Base.eachindex || f === Base.axes
            throw(ArgumentError("ranges are only supported as the range of a for loop (statement $i)"))
        elseif isarray(T)
            # A calculation whose only use is to be returned is the function's result.
            if onlyreturned(ci, i)
                dest = result!(sc, i)
                arraycall!(lines, sc, i, st, dest; declaration=!sc.resultparam)
            else
                arraycall!(lines, sc, i, st, temp!(sc, i, parts(sc, st)); declaration=true)
            end
        elseif compiletime(ci.ssavaluetypes[i])
            return                                # a type or Val: no C meaning
        else
            code, _ = render(sc, i, st)
            name = onlyreturned(ci, i) ? result!(sc, i) : temp!(sc, i, parts(sc, st))
            emit!(lines, sc, "$(ctype(T)) $name = $code;")
        end
    elseif st isa Expr && st.head === :(=)
        # `%i = (x = rhs)`: the SSA value is the value assigned. Refer to it as `x`
        # where that's safe; otherwise keep a temp copy.
        slot, rhs = st.args
        x = sc.names[slot.id]
        if isarray(T)
            store!(lines, sc, i, x, rhs)
        else
            emit!(lines, sc, "$x = $(rhs isa Expr ? first(render(sc, i, rhs)) : value(sc, rhs));")
        end
        if stable(ci, i, slot.id)
            sc.expr[i] = x
            # The value just stored is now also `x`; if it was a temp, later uses
            # (typically the return) can say `x` instead.
            rhs isa Core.SSAValue && !(rhs.id in sc.inlined) && (sc.expr[rhs.id] = x)
        else
            t = temp!(sc, i, contribution(sc, slot))
            emit!(lines, sc, isarray(T) ? "$(declare(valuetype(sc, slot), t));" : "$(ctype(T)) $t = $x;")
            isarray(T) && emit!(lines, sc, "$(copyhelper(sc, slot))($x, $t);")
        end
        isarray(T) && (sc.shapes[i] = valuetype(sc, slot))
    elseif st isa Core.SlotNumber
        # `%i = x`: a read of a variable. Same rule as above.
        x = sc.names[st.id]
        if stable(ci, i, st.id)
            sc.expr[i] = x
        else
            t = temp!(sc, i, contribution(sc, st))
            emit!(lines, sc, isarray(T) ? "$(declare(valuetype(sc, st), t));" : "$(ctype(T)) $t = $x;")
            isarray(T) && emit!(lines, sc, "$(copyhelper(sc, st))($x, $t);")
        end
        isarray(T) && (sc.shapes[i] = valuetype(sc, st))
    elseif st isa Core.SSAValue || st isa Number
        sc.expr[i] = value(sc, st)                 # pure copy; no temp needed
        isarray(T) && (sc.shapes[i] = valuetype(sc, st))
    elseif st isa Core.GotoIfNot || st isa Core.GotoNode
        throw(ArgumentError("control flow not recognised at statement $i"))
    else
        throw(ArgumentError("unsupported statement: $st"))
    end
end

# A statement whose value is a type, a `Val`, or a tuple: compile-time only.
compiletime(t) = t isa Core.Const && !(t.val isa Number) && !(t.val isa AbstractArray)

# Emit `x = rhs` for an array `x`: a helper writing straight into `x` when `x` isn't
# also an operand, otherwise through a temp so the operation can't read what it's
# overwriting.
function store!(lines, sc::Scope, i, x, rhs)
    slot = sc.ci.code[i].args[1].id
    if rhs isa Expr
        f = callee_or_nothing(sc.ci, rhs.args[1])
        if f in (Base.zeros, Base.ones, Base.fill, Base.zero, Base.one) || isconstruction(f) || f === Base.materialize
            construct!(lines, sc, i, rhs, x)
        elseif (f === Base.adjoint || f === Base.transpose) && isarray(valuetype(sc, rhs.args[2]))
            # `B = A'`: a copy into whatever Julia says `B` is. A lazy `Adjoint` (a
            # vector's) is the same storage, known to be transposed; an eager one
            # (StaticArrays materializes a matrix transpose) is copied axes-swapped.
            A = transposed(valuetype(sc, rhs.args[2]))
            R = slottype(sc, slot)
            shape(R) === nothing && (R = A)
            emit!(lines, sc, "$(copyhelper(sc, rhs.args[2], R; from=A))($(value(sc, rhs.args[2])), $x);")
            sc.shapes[i] = R
        elseif x in (value(sc, a) for a in rhs.args[2:end])
            t = temp!(sc, nothing, parts(sc, rhs))
            arraycall!(lines, sc, i, rhs, t; declaration=true)
            emit!(lines, sc, "$(copyhelper(sc, Core.SSAValue(i)))($t, $x);")
        else
            arraycall!(lines, sc, i, rhs, x)
        end
        sc.slotshapes[slot] = sc.shapes[i]
    else
        emit!(lines, sc, "$(copyhelper(sc, rhs))($(value(sc, rhs)), $x);")
        sc.slotshapes[slot] = valuetype(sc, rhs)
    end
end

# Calls that make a whole array: `zeros`/`ones`/`fill`, `zero`/`one`, `SMatrix{…}(I)`,
# block construction and array literals, static constructors, and a broadcast being
# materialized.
function construct!(lines, sc::Scope, i, ex::Expr, dest; declaration::Bool=false)
    f = callee(sc.ci, ex.args[1])
    args = ex.args[2:end]
    f === Base.materialize && return broadcast!(lines, sc, i, args[1], dest; declaration)
    T = widen(sc.ci.ssavaluetypes[i])
    if isconstruction(f) && length(args) == 1 && literal(sc, args[1]) isa LinearAlgebra.UniformScaling
        # `SMatrix{3,3}(I)`: the identity matrix.
        literal(sc, args[1]).λ == 1 || throw(ArgumentError("only `I` itself can be made into a matrix, not a multiple of it (statement $i)"))
        return nullary!(lines, sc, i, identityhelper!(sc.helpers, T), T, dest; declaration)
    end
    isconstruction(f) && return concatenate!(lines, sc, i, f, args, dest; declaration)
    if f in (Base.zero, Base.one) || (f in (Base.zeros, Base.ones) && length(args) == 1 && literal(sc, args[1]) isa Type)
        # `zero(A)`, `zeros(SMatrix{3,4})`, `one(A)`: the size is in the result's type.
        shape(T) === nothing && throw(ArgumentError("$f needs a static array type (statement $i)"))
        f === Base.one && return nullary!(lines, sc, i, identityhelper!(sc.helpers, T), T, dest; declaration)
        f in (Base.zero, Base.zeros) && return nullary!(lines, sc, i, zerohelper!(sc.helpers, T), T, dest; declaration)
        declaration && emit!(lines, sc, declare(T, dest) * ";")
        emit!(lines, sc, "$(fillhelper!(sc.helpers, T))($(eltype(T) <: AbstractFloat ? "1.0" : "1"), $dest);")
        sc.shapes[i] = T
        return
    end
    x = f === Base.fill ? value(sc, args[1]) : "1.0"
    f === Base.fill && (args = args[2:end])
    dims = [literal(sc, a) isa Integer ? literal(sc, a) : throw(ArgumentError("$f needs literal dimensions (statement $i)")) for a in args]
    R = shaped(eltype(T), Tuple(dims))
    f === Base.zeros && return nullary!(lines, sc, i, zerohelper!(sc.helpers, R), R, dest; declaration)
    eltype(T) <: AbstractFloat || f !== Base.ones || (x = "1")
    declaration && emit!(lines, sc, declare(R, dest) * ";")
    emit!(lines, sc, "$(fillhelper!(sc.helpers, R))($x, $dest);")
    sc.shapes[i] = R
end

# Emit a helper that makes an array from nothing: `zero_3x4(out);`, `identity_3x3(out);`.
function nullary!(lines, sc::Scope, i, name, R::Type, dest; declaration::Bool)
    push!(sc.headers, "string.h")
    declaration && emit!(lines, sc, declare(R, dest) * ";")
    emit!(lines, sc, "$name($dest);")
    sc.shapes[i] = R
end

# The compile-time value of `x`, or `nothing` if it has none.
function literal(sc::Scope, x)
    x isa Core.SSAValue && return (t = sc.ci.ssavaluetypes[x.id]; t isa Core.Const ? t.val : nothing)
    x isa GlobalRef && return getfield(x.mod, x.name)
    return x
end

# `hvcat`, `vcat`, `hcat`, `vect`, their `typed_` forms, and static-array constructors.
isconstruction(f) = f in (Base.hvcat, Base.vcat, Base.hcat, Base.vect, Base.typed_hvcat, Base.typed_vcat, Base.typed_hcat) ||
                    (f isa Type && f <: StaticArrays.StaticArray)

# Block construction and array literals. All-scalar literals are assigned element by
# element; anything with an array block goes through a `cat` helper.
function concatenate!(lines, sc::Scope, i, f, args, dest; declaration::Bool=false)
    ci = sc.ci
    tupleof(x) = x isa Core.SSAValue && iscall(ci.code[x.id], Core.tuple) ? ci.code[x.id].args[2:end] :
                 x isa Core.SSAValue && ci.ssavaluetypes[x.id] isa Core.Const ? collect(ci.ssavaluetypes[x.id].val) : nothing
    if f isa Type
        # `SVector(a, b, c)`, `SMatrix{2,2}(t)`: elements in column-major order.
        elems = length(args) == 1 && tupleof(args[1]) !== nothing ? tupleof(args[1]) : args
        R = widen(ci.ssavaluetypes[i])
        all(a -> !isarray(valuetype(sc, a)), elems) || throw(ArgumentError("a static constructor from arrays is not supported (statement $i)"))
        declaration && emit!(lines, sc, declare(R, dest) * ";")
        s = shape(R)
        # Elements arrive column-major; write them row by row, as a person would.
        order = length(s) == 1 ? eachindex(elems) : sort(eachindex(elems); by=k -> ((k - 1) % s[1], (k - 1) ÷ s[1]))
        for k in order
            sub = length(s) == 1 ? "[$(k-1)]" : "[$((k-1) % s[1])][$((k-1) ÷ s[1])]"
            emit!(lines, sc, "$dest$sub = $(value(sc, elems[k]));")
        end
        sc.shapes[i] = R
        return
    end
    f in (Base.typed_hvcat, Base.typed_vcat, Base.typed_hcat) && (args = args[2:end])
    if f in (Base.hvcat, Base.typed_hvcat)
        rows = tupleof(args[1])
        rows === nothing && throw(ArgumentError("hvcat needs literal row lengths (statement $i)"))
        blocks = args[2:end]
        kind = :hvcat
    else
        blocks = args
        rows = f in (Base.vcat, Base.typed_vcat, Base.vect) ? fill(1, length(blocks)) : [length(blocks)]
        kind = f in (Base.vcat, Base.typed_vcat, Base.vect) ? :vcat : :hcat
    end
    types = [valuetype(sc, b) for b in blocks]
    (H, W) = catshape(rows, types)
    T = widen(ci.ssavaluetypes[i])
    E = eltype(T)
    R = shape(T) !== nothing ? T : ndims(T) == 1 ? shaped(E, (H,)) : shaped(E, (H, W))
    ndims(R) == 1 && W != 1 && throw(ArgumentError("a vector can't hold $W columns (statement $i)"))
    declaration && emit!(lines, sc, declare(R, dest) * ";")
    if all(T -> !isarray(T), types)
        # A literal: element by element, row by row.
        k = 1
        for (r, nblocks) in enumerate(rows)
            for c in 1:nblocks
                sub = ndims(R) == 1 ? "[$(r-1)]" : "[$(r-1)][$(c-1)]"
                emit!(lines, sc, "$dest$sub = $(value(sc, blocks[k]));")
                k += 1
            end
        end
    else
        name = cathelper!(sc.helpers, kind, Tuple(rows), types, R)
        emit!(lines, sc, "$name($(join((value(sc, b) for b in blocks), ", ")), $dest);")
    end
    sc.shapes[i] = R
end

# A broadcast tree, from its `broadcasted` root, into `dest`. Julia fuses nested
# broadcasts into one loop; here each level is its own helper, chained through temps.
function broadcast!(lines, sc::Scope, i, root, dest; declaration::Bool=false)
    ci = sc.ci
    node = ci.code[root.id]                       # broadcasted(f, args...)
    f = callee(ci, node.args[2])
    args = node.args[3:end]
    # Inner broadcasts first, each into a temp.
    inputs = Any[]
    for a in args
        if a isa Core.SSAValue && iscall(ci.code[a.id], Base.broadcasted)
            t = temp!(sc, a.id, parts(sc, ci.code[a.id]))
            broadcast!(lines, sc, a.id, a, t; declaration=true)
            push!(inputs, Core.SSAValue(a.id))
        else
            push!(inputs, a)
        end
    end
    types = [valuetype(sc, a) for a in inputs]
    any(isarray, types) || throw(ArgumentError("a broadcast over scalars only (statement $i)"))
    bs = broadcastshape(types)
    bs === nothing && throw(ArgumentError("broadcast: shapes don't line up: $(join(dims.(filter(isarray, types)), ", "))"))
    T = widen(ci.ssavaluetypes[i])
    if isarray(T)
        E = eltype(T)
        R = shape(T) !== nothing ? T :
            T <: LinearAlgebra.Adjoint || T <: LinearAlgebra.Transpose ? Transposed{E, Tuple(reverse(bs)[1:ndims(T)]), ndims(T)} : shaped(E, bs)
    else
        # An inner node of a fused broadcast: the IR only knows it as a `Broadcasted`.
        E = promote_type((isarray(t) ? eltype(t) : t for t in types)...)
        R = all(t -> !isarray(t) || istransposed(t), types) ?
            (nd = maximum(ndims(t) for t in types if isarray(t)); Transposed{E, Tuple(reverse(bs)[1:nd]), nd}) : shaped(E, bs)
    end
    op, cfn = broadcastop(f, length(inputs), E)
    cfn isa String && push!(sc.headers, cfn == "llabs" ? "stdlib.h" : "math.h")
    declaration && emit!(lines, sc, declare(R, dest) * ";")
    name = broadcasthelper!(sc.helpers, op, cfn, types, R)
    emit!(lines, sc, "$name($(join((value(sc, a) for a in inputs), ", ")), $dest);")
    sc.shapes[i] = R
end

# The helper name and C form of a broadcast's function.
function broadcastop(f, n, E)
    f === Base.:+ && return :add, :add
    f === Base.:- && return n == 1 ? (:neg, :neg) : (:sub, :sub)
    f === Base.:* && return :mul, :mul
    f === Base.:/ && return :div, :div
    f === Base.:^ && return :pow, "pow"
    f === Base.abs && return :abs, E <: AbstractFloat ? "fabs" : "llabs"
    f === Base.max && return :max, "fmax"
    f === Base.min && return :min, "fmin"
    for (g, name) in ((Base.sqrt, "sqrt"), (Base.cbrt, "cbrt"), (Base.sin, "sin"), (Base.cos, "cos"), (Base.tan, "tan"),
                      (Base.asin, "asin"), (Base.acos, "acos"), (Base.atan, "atan"), (Base.sinh, "sinh"), (Base.cosh, "cosh"),
                      (Base.tanh, "tanh"), (Base.exp, "exp"), (Base.exp2, "exp2"), (Base.expm1, "expm1"), (Base.log, "log"),
                      (Base.log2, "log2"), (Base.log10, "log10"), (Base.log1p, "log1p"), (Base.floor, "floor"),
                      (Base.ceil, "ceil"), (Base.trunc, "trunc"), (Base.round, "rint"))
        f === g && return Symbol(name == "rint" ? "round" : name), name
    end
    throw(ArgumentError("unsupported broadcast function: $f"))
end

# Emit the helper call for an array operation, writing into `dest`. An n-ary `+` or `*`
# (Julia parses `A + B + C` as one call) is chained through temps.
function arraycall!(lines, sc::Scope, i, ex::Expr, dest; declaration::Bool=false)
    f = callee(sc.ci, ex.args[1])
    args = ex.args[2:end]
    E = eltype(widen(sc.ci.ssavaluetypes[i]))
    if f === LinearAlgebra.cross
        types = (valuetype(sc, args[1]), valuetype(sc, args[2]))
        R = retype(types[1], E)
        declaration && emit!(lines, sc, declare(R, dest) * ";")
        emit!(lines, sc, "$(crosshelper!(sc.helpers, types, R))($(value(sc, args[1])), $(value(sc, args[2])), $dest);")
        sc.shapes[i] = R
        return
    end
    op = f === Base.:+ ? :add :
         f === Base.:- ? (length(args) == 1 ? :neg : :sub) :
         f === Base.:* ? :mul :
         f === Base.copy ? :copy :
         throw(ArgumentError("unsupported array operation: $f"))
    # The result's element type comes from Julia's promotion; its size from the IR if
    # the type carries one, otherwise from the operation's own rule.
    result(types) = (R = widen(sc.ci.ssavaluetypes[i]); shape(R) === nothing ? resulttype(op, types, E) : R)
    acc = args[1]
    accname = value(sc, acc)
    acctype = valuetype(sc, acc)
    R = acctype
    for (n, a) in enumerate(args[2:end])
        last = n == length(args) - 1
        types = (acctype, valuetype(sc, a))
        R = result(types)
        out = last ? dest : temp!(sc, nothing, unique([contribution(sc, acc); contribution(sc, a)]))
        (last ? declaration : true) && emit!(lines, sc, declare(R, out) * ";")
        emit!(lines, sc, "$(helper!(sc.helpers, op, types, R))($accname, $(value(sc, a)), $out);")
        accname, acctype = out, R
    end
    if length(args) == 1
        R = result((acctype,))
        declaration && emit!(lines, sc, declare(R, dest) * ";")
        emit!(lines, sc, "$(helper!(sc.helpers, op, (acctype,), R))($accname, $dest);")
    end
    sc.shapes[i] = R
end

# The copy helper for the array value `x`.
# The helper that copies `x` into a value of type `R`, by default `x`'s own. Between
# like layouts it's a storage copy, named for the storage whether or not the value is
# transposed (`copy_3` for `v'`); into the other layout it swaps the axes as it goes
# (`copy_T2x3`, writing a 3×2).
function copyhelper(sc::Scope, x, R::Type=valuetype(sc, x); from::Type=valuetype(sc, x))
    T = from
    axis(T) == axis(R) && (T = R = plain(R))
    return helper!(sc.helpers, :copy, (T,), R)
end

isarray(T) = T <: AbstractArray

# The named variables behind a call's arguments, for temp naming.
parts(sc::Scope, ex::Expr) = unique(reduce(vcat, (contribution(sc, a) for a in ex.args[2:end]); init=String[]))

"""
    temp!(sc, i, parts) -> name

Name the intermediate value `i`, computed from the named variables `parts`.

Temps are `temp1`, `temp2`, … in order of creation within a function, with the names
of the variables used directly in the calculation appended: `temp1_a_b = a + b`.
Literals contribute nothing (`temp2_a = a + 58.3`), a variable appears at most once
(`temp3_a = a * a`), and a temp passes along only its own suffix, never its base
(`temp4_a_b = temp3_a + b`; `temp5_a = temp2 + a`).

A number is skipped if any of the user's own variables is `temp<N>` or `temp<N>_…`,
so there's never confusion about which is which. If the mangled name would be longer
than the scope's limit, the suffix is dropped and the temp is just `temp<N>`.

There is one rule for what any value contributes, temp or not: its name with any
`temp<N>_` chopped off, split into pieces at `_`. So a user's own `temp4_joel_was_here`
contributes `joel_was_here` exactly as one of ours would, and a plain `temp3` contributes
nothing. See `doc/naming.md`.

`i` may be `nothing` for a temp that doesn't stand for any SSA value.
"""
function temp!(sc::Scope, i, parts)
    sc.counter += 1
    while sc.counter in sc.blocked
        sc.counter += 1
    end
    base = "temp$(sc.counter)"
    name = isempty(parts) ? base : base * "_" * join(parts, "_")
    length(name) > sc.limit && (name = base)
    i === nothing || (sc.expr[i] = name)
    return name
end

# The name for an unnamed result. Only one per block; a second falls back to a temp.
function result!(sc::Scope, i)
    name = sc.result
    sc.result = ""
    isempty(name) && return temp!(sc, i, String[])
    sc.expr[i] = name
    return name
end

# Is SSA value `i` used by nothing but return statements?
function onlyreturned(ci, i)
    users = [st for st in ci.code if uses(st, i)]
    return !isempty(users) && all(st -> st isa Core.ReturnNode, users)
end

# The pieces an IR value contributes to a temp's suffix. Literals contribute nothing.
# Anything named contributes its name, minus a leading `temp<N>` (and its `_`), split
# at `_` — the same rule whether the name is one of our temps or the user's own.
function contribution(sc::Scope, x)
    x isa Core.SSAValue || x isa Core.SlotNumber || return String[]
    x isa Core.SSAValue && !(x.id in sc.inlined) && !haskey(sc.expr, x.id) && return String[]   # a constant load
    x isa Core.SSAValue && x.id in sc.inlined && return unique(reduce(vcat, (contribution(sc, a) for a in sc.ci.code[x.id].args[2:end]); init=String[]))
    name = replace(value(sc, x), r"^temp\d+_?" => "")
    return filter(!isempty, split(name, "_"))
end

# Can SSA value `i`, which holds the value of `slot` at that point, be written as the
# slot's name at every use? Only if the slot isn't reassigned in between. The textual
# scan is sound for Julia's structured lowering: everything executed between a value's
# definition and a use of it lies between them in the statement list too.
function stable(ci, i, slot)
    for (u, st) in enumerate(ci.code)
        u > i && uses(st, i) || continue
        any(k -> assigns(ci.code[k], slot), i+1:u-1) && return false
    end
    return true
end

uses(x, i) = x isa Core.SSAValue   ? x.id == i :
             x isa Expr            ? any(a -> uses(a, i), x.args) :
             x isa Core.ReturnNode ? isdefined(x, :val) && uses(x.val, i) :
             x isa Core.GotoIfNot  ? uses(x.cond, i) : false

assigns(st, slot) = st isa Expr && st.head === :(=) && st.args[1].id == slot

# C precedence levels used by `render`.
const PRIMARY, UNARY, MUL, ADD, SHIFT, REL, EQ, BAND, BXOR, BOR, LAND, LOR = 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4

"""
    render(sc, i, ex) -> (text, precedence)

The C expression for the scalar call `ex`, whose result is SSA value `i`.
"""
function render(sc::Scope, i, ex::Expr)
    ci = sc.ci
    f = callee(ci, ex.args[1])
    args = ex.args[2:end]
    T = widen(ci.ssavaluetypes[i])
    n = length(args)
    op(sym, prec) = (join([operand(sc, args[1], prec); [operand(sc, a, prec; right=true) for a in args[2:end]]], " $sym "), prec)
    unary(sym) = (sym * operand(sc, args[1], UNARY), UNARY)
    fn(name, hdr="math.h") = (push!(sc.headers, hdr); ("$name(" * join((expression(sc, a)[1] for a in args), ", ") * ")", PRIMARY))
    floating = T <: AbstractFloat

    # The determinant: a helper that returns the scalar.
    if f === LinearAlgebra.det && n == 1 && isarray(valuetype(sc, args[1]))
        return "$(dethelper!(sc.helpers, valuetype(sc, args[1]), T))($(value(sc, args[1])))", PRIMARY
    end
    # A dot product, or a row times a column: a helper that returns the scalar.
    if (f === LinearAlgebra.dot || f === Base.:*) && n == 2 && all(a -> isarray(valuetype(sc, a)), args) &&
       ndims(valuetype(sc, args[1])) == 1 && ndims(valuetype(sc, args[2])) == 1
        types = (valuetype(sc, args[1]), valuetype(sc, args[2]))
        f === Base.:* && !(isrow(types[1]) && !isrow(types[2])) && throw(ArgumentError("vector * vector is only defined for a row times a column (statement $i)"))
        name = scalarhelper!(sc.helpers, f === LinearAlgebra.dot ? :dot : :mul, types, T)
        return "$name($(value(sc, args[1])), $(value(sc, args[2])))", PRIMARY
    end

    # Arithmetic.
    f === Base.:+ && return n == 1 ? expression(sc, args[1]) : op("+", ADD)
    f === Base.:- && return n == 1 ? unary("-") : op("-", ADD)
    f === Base.:* && return op("*", MUL)
    if f === Base.:/
        if all(a -> valuetype(sc, a) <: Integer, args)
            # Julia `/` always produces a float. C promotes an integer operand to the
            # other's floating type on its own, so only integer-by-integer needs help:
            # literals get `.0`, anything else a cast to the result type.
            parts = [a isa Integer ? "$a.0" : "($(ctype(T)))" * operand(sc, a, UNARY) for a in args]
            return join(parts, " / "), MUL
        end
        return op("/", MUL)
    end
    f === Base.div && return op("/", MUL)
    f === Base.rem && return floating ? fn("fmod") : op("%", MUL)
    if f === Base.mod
        floating && throw(ArgumentError("mod on floats is not yet supported (statement $i)"))
        a, b = operand(sc, args[1], MUL), operand(sc, args[2], MUL; right=true)
        return "(($a % $b) + $b) % $b", MUL
    end
    if f === Base.literal_pow
        p = ci.ssavaluetypes[args[3].id].val
        p isa Val || throw(ArgumentError("unsupported power (statement $i)"))
        e = typeof(p).parameters[1]
        x = operand(sc, args[2], MUL)
        e == 2 && return "$x * $x", MUL
        e == 3 && return "$x * $x * $x", MUL
        e == -1 && floating && return "1.0 / $x", MUL
        floating && (push!(sc.headers, "math.h"); return "pow($(expression(sc, args[2])[1]), $(Float64(e)))", PRIMARY)
        throw(ArgumentError("integer power $e is not supported; only 2 and 3 (statement $i)"))
    end
    if f === Base.:^
        floating || throw(ArgumentError("integer ^ with a non-literal exponent is not supported (statement $i)"))
        return fn("pow")
    end

    # Comparison and logic.
    f === Base.:<  && return op("<", REL)
    f === Base.:<= && return op("<=", REL)
    f === Base.:>  && return op(">", REL)
    f === Base.:>= && return op(">=", REL)
    f === Base.:(==) && return op("==", EQ)
    f === Base.:!= && return op("!=", EQ)
    f === Base.:(===) && return op("==", EQ)
    f === Base.:! && return unary("!")
    f === Base.not_int && return unary("!")
    f === Base.:& && return op("&", BAND)
    f === Base.:| && return op("|", BOR)
    f === Base.xor && return op("^", BXOR)
    f === Base.:<< && return op("<<", SHIFT)
    f === Base.:>> && return op(">>", SHIFT)
    f === Base.:~ && return unary("~")

    # Math.
    if floating
        f === Base.abs   && return fn("fabs")
        f === Base.max   && return fn("fmax")
        f === Base.min   && return fn("fmin")
        f === Base.round && n == 1 && return fn("rint")            # Julia rounds to even; so does rint
        f === Base.atan  && n == 2 && return fn("atan2")
        for (g, name) in ((Base.sqrt, "sqrt"), (Base.cbrt, "cbrt"), (Base.sin, "sin"), (Base.cos, "cos"), (Base.tan, "tan"),
                          (Base.asin, "asin"), (Base.acos, "acos"), (Base.atan, "atan"), (Base.sinh, "sinh"),
                          (Base.cosh, "cosh"), (Base.tanh, "tanh"), (Base.exp, "exp"), (Base.exp2, "exp2"),
                          (Base.expm1, "expm1"), (Base.log, "log"), (Base.log2, "log2"), (Base.log10, "log10"),
                          (Base.log1p, "log1p"), (Base.floor, "floor"), (Base.ceil, "ceil"), (Base.trunc, "trunc"),
                          (Base.hypot, "hypot"), (Base.copysign, "copysign"))
            f === g && n == length(args) && !(args[1] isa Type) && return fn(name)
        end
    elseif T <: Integer
        f === Base.abs && return T === Int64 ? fn("llabs", "stdlib.h") : T === Int32 ? fn("abs", "stdlib.h") : throw(ArgumentError("abs on $T"))
        if f === Base.max || f === Base.min
            a, b = expression(sc, args[1])[1], expression(sc, args[2])[1]
            return "($a $(f === Base.max ? ">" : "<") $b ? $a : $b)", PRIMARY
        end
        # `round(Int, x)`, `floor(Int, x)`, …: a math function then a cast.
        if f in (Base.round, Base.floor, Base.ceil, Base.trunc) && n == 2
            g = f === Base.round ? "rint" : f === Base.floor ? "floor" : f === Base.ceil ? "ceil" : "trunc"
            push!(sc.headers, "math.h")
            return "($(ctype(T)))$g($(expression(sc, args[2])[1]))", UNARY
        end
    end

    # Conversions: a call to a type.
    f isa Type && n == 1 && return "($(ctype(T)))" * operand(sc, args[1], UNARY), UNARY

    # Arrays, as scalars: an element, or a size.
    f === Base.getindex && return index(sc, args[1], args[2:end]), PRIMARY
    f === Base.length && return string(prod(shape(valuetype(sc, args[1])))), PRIMARY
    f === Base.size && n == 2 && return string(shape(valuetype(sc, args[1]))[args[2]]), PRIMARY

    throw(ArgumentError("unsupported call: $f (statement $i)"))
end

# `A[i]`, `A[i, j]`: Julia's 1-based indices become 0-based.
function index(sc::Scope, A, idx)
    T = valuetype(sc, A)
    isarray(T) || throw(ArgumentError("indexing into a $T"))
    length(idx) == ndims(T) || throw(ArgumentError("$(length(idx)) indices into a $(ndims(T))-dimensional array"))
    subs = map(idx) do k
        k isa Integer && return string(k - 1)
        text, p = expression(sc, k)
        return (p < ADD ? "($text)" : text) * " - 1"
    end
    return value(sc, A) * join("[$s]" for s in subs)
end

# C code for an IR value (a name or literal; use `expression` for inlined calls).
function value(sc::Scope, x)
    if x isa Core.SSAValue
        x.id in sc.inlined && return first(expression(sc, x))
        haskey(sc.expr, x.id) && return sc.expr[x.id]
        sc.ci.code[x.id] isa GlobalRef && return value(sc, sc.ci.code[x.id])
        sc.ci.code[x.id] isa Core.SlotNumber && return sc.names[sc.ci.code[x.id].id]   # a read inside a loop header
        throw(ArgumentError("value of statement $(x.id) is not available in C"))
    end
    x isa Core.SlotNumber && return sc.names[x.id]
    x isa Bool            && return x ? "true" : "false"
    x isa Integer         && return string(x)
    x isa AbstractFloat   && return isinf(x) ? (push!(sc.headers, "math.h"); x > 0 ? "INFINITY" : "-INFINITY") :
                                    isnan(x) ? (push!(sc.headers, "math.h"); "NAN") : repr(x)
    x isa Irrational      && return (push!(sc.headers, "math.h"); x === pi ? "M_PI" : x === ℯ ? "M_E" : repr(Float64(x)))
    x isa GlobalRef       && return value(sc, getfield(x.mod, x.name))
    throw(ArgumentError("unsupported value: $(repr(x))"))
end

# The type of a value: what inference says, except that an array whose size the IR
# doesn't know is given as the shaped stand-in the transpiler tracks for it.
function valuetype(sc::Scope, x)
    x isa Core.SSAValue   && return get(sc.shapes, x.id, widen(sc.ci.ssavaluetypes[x.id]))
    x isa Core.SlotNumber && return get(sc.slotshapes, x.id, widen(sc.ci.slottypes[x.id]))
    x isa GlobalRef       && return typeof(getfield(x.mod, x.name))
    return typeof(x)
end

# The function object a call refers to. In unoptimized IR the callee is usually an
# SSA value whose statement is a GlobalRef.
function callee(ci, x)
    if x isa Core.SSAValue
        t = ci.ssavaluetypes[x.id]
        t isa Core.Const && (t.val isa Function || t.val isa Type) && return t.val
        return callee(ci, ci.code[x.id])
    end
    x isa GlobalRef     && return getfield(x.mod, x.name)
    x isa Expr && x.head === :call && ci.ssavaluetypes !== nothing && return throw(ArgumentError("unsupported callee: $x"))
    (x isa Function || x isa Type || x isa Colon) && return x
    throw(ArgumentError("unsupported callee: $x"))
end

# Inference wraps known constants as Core.Const and partially-known structs as
# Core.PartialStruct; we only want the type.
widen(t) = normalize(t isa Core.Const ? typeof(t.val) :
                     t isa Core.PartialStruct ? t.typ :
                     t isa Type ? t : throw(ArgumentError("unsupported type lattice element: $t")))
