# Typed lowered IR -> C source, one concrete MethodInstance at a time.
#
# Walks the *unoptimized* typed CodeInfo (`code_typed(optimize=false)`): every value
# carries its inferred concrete type, local variable names survive, and arithmetic
# appears as calls to +, -, *, / rather than intrinsics. Julia locals become C locals
# named by the rules in `name.jl`; intermediate values become temps named by the rules
# on `temp!`. Operations on arrays become calls to helpers generated by `helper.jl`.

include("name.jl")
include("type.jl")
include("helper.jl")

# Per-function state for naming intermediate values.
mutable struct Scope
    ci::Core.CodeInfo
    names::Vector{String}               # C name of each slot (index 1 is `#self#`, unused)
    result::String                      # name for an unnamed result, `result` unless that's taken
    resultname::String                  # the same, kept after `result` is claimed
    resultparam::Bool                   # the result is an array, passed out through a parameter
    staticarray::Bool                   # every array is fixed-size; dynamic operations are errors
    limit::Int                          # longest temp name we're willing to mangle to
    blocked::Set{Int}                   # temp numbers already taken by the user's own names
    counter::Int
    expr::Dict{Int, String}             # SSA id -> the C expression that stands for it
    helpers::Dict{String, String}       # shared across the whole output; see helper.jl
end

function Scope(ci::Core.CodeInfo, limit::Integer, staticarray::Bool, helpers)
    names = ["#self#"; identifiers(string.(ci.slotnames[2:end]))]
    result = "result"
    while result in names
        result *= "_"
    end
    blocked = Set{Int}()
    for s in names
        m = match(r"^temp(\d+)(_.*)?$", s)
        m === nothing || push!(blocked, parse(Int, m[1]))
    end
    return Scope(ci, names, result, result, false, staticarray, limit, blocked, 0, Dict{Int, String}(), helpers)
end

"""
    cfunction(name, mi, helpers; templimit=40, staticarray=true) -> (prototype, definition)

C source for the concrete MethodInstance `mi`, named `name` in C. Any array helpers it
needs are added to `helpers`.
"""
function cfunction(name::AbstractString, mi::Core.MethodInstance, helpers::Dict{String, String};
                   templimit::Integer=40, staticarray::Bool=true)
    ci, rettype = only(Base.code_typed_by_type(mi.specTypes; optimize=false))
    sc = Scope(ci, templimit, staticarray, helpers)

    params = [declare(widen(ci.slottypes[i]), sc.names[i]; constant=isarray(widen(ci.slottypes[i]))) for i in 2:ci.nargs]
    if isarray(rettype)
        # C can't return an array; it comes out through a trailing parameter, which
        # takes the result's name.
        push!(params, declare(rettype, sc.resultname))
        sc.resultparam = true
        signature = "void $name($(join(params, ", ")))"
    else
        signature = "$(ctype(rettype)) $name($(isempty(params) ? "void" : join(params, ", ")))"
    end

    lines = String[]
    for i in ci.nargs+1:length(ci.slotnames)      # locals, declared up front
        push!(lines, declare(widen(ci.slottypes[i]), sc.names[i]) * ";")
    end
    for (i, st) in enumerate(ci.code)
        statement!(lines, sc, i, st)
    end
    return signature * ";", signature * " {\n" * join("    " .* lines, "\n") * "\n}\n"
end

# Emit the C for one IR statement, appending to `lines`.
function statement!(lines, sc::Scope, i, st)
    ci = sc.ci
    st === nothing && return
    st isa GlobalRef && return                    # constant load; resolved where it's used
    st isa Expr && st.head in (:meta, :code_coverage_effect) && return
    T = widen(ci.ssavaluetypes[i])
    if st isa Core.ReturnNode
        v = value(sc, st.val)
        if sc.resultparam
            # An array result is written into the out parameter; if it isn't there
            # already, copy it. No `return` needed from a void function.
            v == sc.resultname || push!(lines, "$(copyhelper(sc, st.val))($v, $(sc.resultname));")
        else
            push!(lines, "return $v;")
        end
    elseif st isa Expr && st.head === :call
        if isarray(T)
            # A calculation whose only use is to be returned is the function's result.
            if onlyreturned(ci, i)
                dest = result!(sc, i)
                sc.resultparam || push!(lines, declare(T, dest) * ";")
            else
                dest = temp!(sc, i, parts(sc, st))
                push!(lines, declare(T, dest) * ";")
            end
            arraycall!(lines, sc, i, st, dest)
        else
            code = call(sc, i, st)
            name = onlyreturned(ci, i) ? result!(sc, i) : temp!(sc, i, parts(sc, st))
            push!(lines, "$(ctype(T)) $name = $code;")
        end
    elseif st isa Expr && st.head === :(=)
        # `%i = (x = rhs)`: the SSA value is the value assigned. Refer to it as `x`
        # where that's safe; otherwise keep a temp copy.
        slot, rhs = st.args
        x = sc.names[slot.id]
        if isarray(T)
            store!(lines, sc, i, x, rhs)
        else
            push!(lines, "$x = $(rhs isa Expr ? call(sc, i, rhs) : value(sc, rhs));")
        end
        if stable(ci, i, slot.id)
            sc.expr[i] = x
            # The value just stored is now also `x`; if it was a temp, later uses
            # (typically the return) can say `x` instead.
            rhs isa Core.SSAValue && (sc.expr[rhs.id] = x)
        else
            t = temp!(sc, i, contribution(sc, slot))
            push!(lines, isarray(T) ? "$(declare(T, t));" : "$(ctype(T)) $t = $x;")
            isarray(T) && push!(lines, "$(copyhelper(sc, slot))($x, $t);")
        end
    elseif st isa Core.SlotNumber
        # `%i = x`: a read of a variable. Same rule as above.
        x = sc.names[st.id]
        if stable(ci, i, st.id)
            sc.expr[i] = x
        else
            t = temp!(sc, i, contribution(sc, st))
            push!(lines, isarray(T) ? "$(declare(T, t));" : "$(ctype(T)) $t = $x;")
            isarray(T) && push!(lines, "$(copyhelper(sc, st))($x, $t);")
        end
    elseif st isa Core.SSAValue || st isa Number
        sc.expr[i] = value(sc, st)                 # pure copy; no temp needed
    else
        throw(ArgumentError("unsupported statement: $st"))
    end
end

# Emit `x = rhs` for an array `x`: a helper writing straight into `x` when `x` isn't
# also an operand, otherwise through a temp so the operation can't read what it's
# overwriting.
function store!(lines, sc::Scope, i, x, rhs)
    if rhs isa Expr
        if x in (value(sc, a) for a in rhs.args[2:end])
            t = temp!(sc, nothing, parts(sc, rhs))
            push!(lines, declare(widen(sc.ci.ssavaluetypes[i]), t) * ";")
            arraycall!(lines, sc, i, rhs, t)
            push!(lines, "$(copyhelper(sc, Core.SSAValue(i)))($t, $x);")
        else
            arraycall!(lines, sc, i, rhs, x)
        end
    else
        push!(lines, "$(copyhelper(sc, rhs))($(value(sc, rhs)), $x);")
    end
end

# Emit the helper call for an array operation, writing into `dest`. An n-ary `+` or `*`
# (Julia parses `A + B + C` as one call) is chained through temps.
function arraycall!(lines, sc::Scope, i, ex::Expr, dest)
    f = callee(sc.ci, ex.args[1])
    args = ex.args[2:end]
    op = f === Base.:+ ? :add :
         f === Base.:- ? (length(args) == 1 ? :neg : :sub) :
         f === Base.:* ? :mul :
         f === Base.copy ? :copy :
         throw(ArgumentError("unsupported array operation: $f"))
    R = widen(sc.ci.ssavaluetypes[i])
    acc = args[1]
    accname = value(sc, acc)
    acctype = valuetype(sc.ci, acc)
    for (n, a) in enumerate(args[2:end])
        last = n == length(args) - 1
        out = last ? dest : temp!(sc, nothing, unique([contribution(sc, acc); contribution(sc, a)]))
        last || push!(lines, declare(R, out) * ";")
        name = helper!(sc.helpers, op, (acctype, valuetype(sc.ci, a)), R)
        push!(lines, "$name($accname, $(value(sc, a)), $out);")
        accname, acctype = out, R
    end
    if length(args) == 1
        name = helper!(sc.helpers, op, (acctype,), R)
        push!(lines, "$name($accname, $dest);")
    end
end

# The copy helper for the array value `x`.
copyhelper(sc::Scope, x) = (T = valuetype(sc.ci, x); helper!(sc.helpers, :copy, (T,), T))

isarray(T) = T <: AbstractArray

# The named variables behind a call's arguments, for temp naming.
parts(sc::Scope, ex::Expr) = unique(reduce(vcat, (contribution(sc, a) for a in ex.args[2:end]); init=String[]))

"""
    temp!(sc, i, parts) -> name

Name the intermediate value `i`, computed from the named variables `parts`.

Temps are `temp1`, `temp2`, … in order of creation within a function, with the names
of the variables used directly in the calculation appended: `temp1_a_b = a + b`.
Literals contribute nothing (`temp2_a = a + 58.3`), a variable appears at most once
(`temp3_a = a * a`), and a temp passes along only its own suffix, never its base
(`temp4_a_b = temp3_a + b`; `temp5_a = temp2 + a`).

A number is skipped if any of the user's own variables is `temp<N>` or `temp<N>_…`,
so there's never confusion about which is which. If the mangled name would be longer
than the scope's limit, the suffix is dropped and the temp is just `temp<N>`.

There is one rule for what any value contributes, temp or not: its name with any
`temp<N>_` chopped off, split into pieces at `_`. So a user's own `temp4_joel_was_here`
contributes `joel_was_here` exactly as one of ours would, and a plain `temp3` contributes
nothing. See `doc/naming.md`.

`i` may be `nothing` for a temp that doesn't stand for any SSA value.
"""
function temp!(sc::Scope, i, parts)
    sc.counter += 1
    while sc.counter in sc.blocked
        sc.counter += 1
    end
    base = "temp$(sc.counter)"
    name = isempty(parts) ? base : base * "_" * join(parts, "_")
    length(name) > sc.limit && (name = base)
    i === nothing || (sc.expr[i] = name)
    return name
end

# The name for an unnamed result. Only one per function; a second falls back to a temp.
function result!(sc::Scope, i)
    name = sc.result
    sc.result = ""
    isempty(name) && return temp!(sc, i, String[])
    sc.expr[i] = name
    return name
end

# Is SSA value `i` used by nothing but return statements?
function onlyreturned(ci, i)
    users = [st for st in ci.code if uses(st, i)]
    return !isempty(users) && all(st -> st isa Core.ReturnNode, users)
end

# The pieces an IR value contributes to a temp's suffix. Literals contribute nothing.
# Anything named contributes its name, minus a leading `temp<N>` (and its `_`), split
# at `_` — the same rule whether the name is one of our temps or the user's own.
function contribution(sc::Scope, x)
    x isa Core.SSAValue || x isa Core.SlotNumber || return String[]
    name = replace(value(sc, x), r"^temp\d+_?" => "")
    return filter(!isempty, split(name, "_"))
end

# Can SSA value `i`, which holds the value of `slot` at that point, be written as the
# slot's name at every use? Only if the slot isn't reassigned in between.
# (Assumes straight-line code — revisit when control flow arrives.)
function stable(ci, i, slot)
    for (u, st) in enumerate(ci.code)
        u > i && uses(st, i) || continue
        any(k -> assigns(ci.code[k], slot), i+1:u-1) && return false
    end
    return true
end

uses(x, i) = x isa Core.SSAValue   ? x.id == i :
             x isa Expr            ? any(a -> uses(a, i), x.args) :
             x isa Core.ReturnNode ? isdefined(x, :val) && uses(x.val, i) : false

assigns(st, slot) = st isa Expr && st.head === :(=) && st.args[1].id == slot

# C code for a scalar call expression whose result is SSA value `i`.
function call(sc::Scope, i, ex::Expr)
    ci = sc.ci
    f = callee(ci, ex.args[1])
    op = coperator(f)
    args = [value(sc, a) for a in ex.args[2:end]]
    if length(args) == 1
        return "$op($(args[1]))"                    # parenthesised so `- -3` can't become `--3`
    end
    if f === Base.:/ && all(a -> valuetype(ci, a) <: Integer, ex.args[2:end])
        # Julia `/` always produces a float. C promotes an integer operand to the
        # other operand's floating type on its own, so only integer-by-integer needs
        # help. Literals get `.0`; anything else gets a cast to the result type.
        T = ctype(widen(ci.ssavaluetypes[i]))
        args = [a isa Integer ? "$a.0" : "($T)$c" for (a, c) in zip(ex.args[2:end], args)]
    end
    return join(args, " $op ")                      # Julia parses a+b+c as +(a,b,c), so n-ary is normal
end

# C code for an IR value.
function value(sc::Scope, x)
    x isa Core.SSAValue   && return sc.expr[x.id]
    x isa Core.SlotNumber && return sc.names[x.id]
    x isa Bool            && return x ? "true" : "false"
    x isa Integer         && return string(x)
    x isa AbstractFloat   && return repr(x)
    throw(ArgumentError("unsupported value: $(repr(x))"))
end

# The inferred type of a value.
function valuetype(ci, x)
    x isa Core.SSAValue   && return widen(ci.ssavaluetypes[x.id])
    x isa Core.SlotNumber && return widen(ci.slottypes[x.id])
    return typeof(x)
end

# The function object a call refers to. In unoptimized IR the callee is usually an
# SSA value whose statement is a GlobalRef.
function callee(ci, x)
    x isa Core.SSAValue && return callee(ci, ci.code[x.id])
    x isa GlobalRef     && return getfield(x.mod, x.name)
    throw(ArgumentError("unsupported callee: $x"))
end

function coperator(f)
    f === Base.:+ && return "+"
    f === Base.:- && return "-"
    f === Base.:* && return "*"
    f === Base.:/ && return "/"
    throw(ArgumentError("unsupported call: $f"))
end

# Inference wraps known constants as Core.Const and partially-known structs as
# Core.PartialStruct; we only want the type.
widen(t) = t isa Core.Const ? typeof(t.val) :
           t isa Core.PartialStruct ? t.typ :
           t isa Type ? t : throw(ArgumentError("unsupported type lattice element: $t"))
