# Typed lowered IR -> C source, one concrete MethodInstance at a time.
#
# Walks the *unoptimized* typed CodeInfo (`code_typed(optimize=false)`): every value
# carries its inferred concrete type, local variable names survive, and arithmetic
# appears as calls to +, -, *, / rather than intrinsics. Julia locals become C locals
# named by the rules in `name.jl`; intermediate values become temps named by the rules
# on `temp!`. Operations on arrays become calls to helpers generated by `helper.jl`;
# control flow is recovered from gotos by `flow.jl`.

include("name.jl")
include("type.jl")
include("prose.jl")
include("helper.jl")
include("source.jl")

# State shared by every function in one output file.
mutable struct Program
    helpers::Dict{String, String}                                  # see helper.jl
    headers::Set{String}                                           # standard headers the output needs
    calls::Dict{Core.MethodInstance, String}                       # every transpiled instance -> its C name
    pending::Vector{Tuple{Core.MethodInstance, Vector{Type}, String}}   # found through a call, not generated yet
    names::Set{String}                                             # C function names taken so far
    foreign::Dict{String, String}                                  # a `ccall`ed symbol -> its prototype
    structs::Vector{Pair{Type, String}}                            # struct typedefs, dependencies first
    precise::Bool                                                  # print every digit of a floating value, not `%g`
    width::Int                                                     # the longest line; scalar expressions wrap past it
    portable::Bool                                                 # our own `LEGIBLEC_PI` macros instead of POSIX `M_PI`
    macros::Set{String}                                            # the constants used: "PI", "E"
    effects::Dict{Core.MethodInstance, Set{Symbol}}                # what a user function does besides compute (see `effects!`)
end
Program(; precise::Bool=false, width::Integer=100, portable::Bool=false) =
    Program(Dict{String, String}(), Set(["stdint.h", "stdbool.h"]), Dict{Core.MethodInstance, String}(),
            Tuple{Core.MethodInstance, Vector{Type}, String}[], Set{String}(), Dict{String, String}(), Pair{Type, String}[], precise, width,
            portable, Set{String}(), Dict{Core.MethodInstance, Set{Symbol}}())

# The mathematical constants, for when the output defines its own macros (`portable`):
# each is emitted as the double it rounds to, in the shortest form that reads back to
# it, with the symbol in a comment (`transpile` writes the lines).
const constants = Dict("PI" => π, "E" => ℯ)

# Per-function state.
mutable struct Scope
    ci::Core.CodeInfo
    names::Vector{String}               # C name of each slot (index 1 is `#self#`, unused)
    result::String                      # name for an unnamed result, `result` unless that's taken
    resultname::String                  # the same, kept after `result` is claimed
    resultparam::Bool                   # the result is an array, passed out through a parameter
    staticarray::Bool                   # every array is fixed-size; dynamic operations are errors
    limit::Int                          # longest temp name we're willing to mangle to
    blocked::Set{Int}                   # temp numbers already taken by the user's own names
    counter::Int
    expr::Dict{Int, String}             # SSA id -> the C expression that stands for it
    helpers::Dict{String, String}       # shared across the whole output; see helper.jl
    headers::Set{String}                # shared: standard headers the output needs
    # Sizes the IR doesn't know: a regular array's type has none, so the transpiler
    # tracks a shaped stand-in for each SSA value and slot that holds one.
    shapes::Dict{Int, Type}             # SSA id -> shaped type
    slotshapes::Dict{Int, Type}         # slot id -> shaped type
    rettype::Type                       # the (shaped) type actually returned
    # Source annotations (see source.jl): the file, each statement's line, how far
    # into the file the comments have been emitted, and whether code lines are copied.
    src::Union{Source, Nothing}
    stmtline::Vector{Int}
    cursor::Int
    copycode::Bool
    # Control flow (see flow.jl).
    depth::Int                          # current nesting, for indentation
    inlined::Set{Int}                   # SSA ids rendered inside conditions, not as temps
    skipped::Set{Int}                   # statements consumed by a construct; never emitted
    hidden::Set{Int}                    # slots never declared: iterator state, loop variables, aliases
    mutated::Set{Int}                   # array slots written through setindex!
    loops::Vector{Tuple{Int, Int}}      # enclosing loops: (break target, continue target)
    fors::Dict{Int, Any}
    whiles::Dict{Int, Any}
    prog::Program
    # Step comments (see `step!`): each is (first line, last line, text, Julia line).
    steps::Vector{Tuple{Int, Int, String, Int}}
    current::Int                        # the statement being emitted
    math::Dict{Int, String}             # SSA id -> the math a rendered helper call computes
    # An array parameter Julia reassigns: its working copy's slot -> the parameter's
    # slot. The copy is made at the top of the function, under a comment saying why.
    rebound::Dict{Int, Int}
    declared::Set{Int}                  # slots already declared, at their first assignment
    blockstart::Int                     # where the current top-level statement or construct began
    # Lines to insert once the walk is done, (at, priority, text or () -> text): hoisted
    # declarations and the comments that go above a multi-line step. Deferred so that
    # nothing shifts under the line numbers recorded along the way.
    inserts::Vector{Tuple{Int, Int, Any}}
    # Array negations folded into the scalar of the multiply or divide that consumes
    # them: `-x / s` is `div_3_s(x, -s, …)`. The SSA value reads as the array itself.
    negated::Set{Int}
end

function Scope(ci::Core.CodeInfo, mi::Core.MethodInstance, sig, limit::Integer, staticarray::Bool, prog::Program, copycode::Bool, blocked)
    names = ["#self#"; identifiers([isempty(string(s)) ? "#s$i" : string(s) for (i, s) in enumerate(ci.slotnames[2:end])]; blocked)]
    hidden = Set{Int}(i for (i, s) in enumerate(ci.slotnames) if i > 1 && isempty(string(s)))
    result = "result"
    while result in names
        result *= "_"
    end
    blocked = Set{Int}()
    for s in names
        m = match(r"^temp(\d+)(_.*)?$", s)
        m === nothing || push!(blocked, parse(Int, m[1]))
    end
    slotshapes = Dict{Int, Type}(i + 1 => T for (i, T) in enumerate(sig) if isarray(T))
    src = Source(mi.def)
    stmtline = statementlines(mi, length(ci.code))   # from the IR, so it works without the file
    return Scope(ci, names, result, result, false, staticarray, limit, blocked, 0, Dict{Int, String}(), prog.helpers, prog.headers,
                 Dict{Int, Type}(), slotshapes, Union{}, src, stmtline, src === nothing ? 0 : src.first - 1, copycode,
                 0, Set{Int}(), Set{Int}(), hidden, Set{Int}(), Tuple{Int, Int}[], Dict{Int, Any}(), Dict{Int, Any}(), prog,
                 Tuple{Int, Int, String, Int}[], 0, Dict{Int, String}(), Dict{Int, Int}(), Set{Int}(), 1,
                 Tuple{Int, Int, Any}[], Set{Int}())
end

include("flow.jl")
include("io.jl")
include("move.jl")

"""
    cfunction(name, mi, sig, helpers, headers; templimit=40, staticarray=true, source=true) -> (prototype, definition)

C source for the concrete MethodInstance `mi`, named `name` in C, with argument types
`sig` — the instance's own types, except that a regular array is given as a shaped
stand-in carrying the size the IR doesn't know. Any array helpers it needs are added
to `helpers`, and any standard headers to `headers`.
"""
function cfunction(name::AbstractString, mi::Core.MethodInstance, sig, prog::Program;
                   templimit::Integer=40, staticarray::Bool=true, source::Bool=true, blocked=())
    ci, rettype = only(Base.code_typed_by_type(mi.specTypes; optimize=false))
    rettype === Union{} && throw(ArgumentError("$(mi.def.name) never returns normally according to inference: something in it always throws"))
    sc = Scope(ci, mi, sig, templimit, staticarray, prog, source, blocked)
    sc.resultparam = isarray(rettype)
    sc.rettype = widen(rettype)
    for T in [sig; sc.rettype]
        structdef!(prog, T)
    end
    if sc.resultparam
        # An array comes out through a parameter, and an output parameter is `out` —
        # `result` is kept for a returned scalar (see naming.md).
        sc.result = sc.resultname = free("out", sc.names)
    end
    analyze!(sc)

    body = String[]
    block!(body, sc, 1, length(ci.code))
    if sc.src !== nothing && sc.src.last > sc.cursor   # whatever follows the last statement
        separate!(body, sc)
        annotate!(body, sc, sc.src.last)
    end
    steps!(body, sc)
    # Hoisted declarations and above-the-line comments go in last, from the bottom up so
    # that nothing shifts; at one place a declaration comes first, then its copy, then a
    # step comment.
    for (at, _, text) in sort(sc.inserts; by=t -> (-t[1], -t[2]))
        insert!(body, at, text isa String ? text : text())
    end
    # A statement's blank line never sits against the closing brace of its block.
    body = [l for (k, l) in enumerate(body) if !(isempty(l) && (k == length(body) || startswith(lstrip(body[k+1]), "}")))]
    # Anything not declared along the way (a variable assigned only where the walk
    # doesn't look, such as a loop header) is declared at the top.
    lines = [declare(slottype(sc, i), sc.names[i]) * ";" for i in ci.nargs+1:length(ci.slotnames) if !(i in sc.hidden) && !(i in sc.declared)]
    # Array parameters the function reassigns are worked on as copies, made here at
    # the top in one block with the reason above it, so the copy doesn't look gratuitous.
    if !isempty(sc.rebound)
        copies = sort(collect(sc.rebound); by=last)
        names = [sc.names[p] for (_, p) in copies]
        listed = length(names) == 1 ? names[1] :
                 length(names) == 2 ? names[1] * " and " * names[2] :
                 join(names[1:end-1], ", ") * ", and " * names[end]
        push!(lines, "// copy $listed to prevent modification within this function")
        push!(sc.headers, "string.h")
        for (s, p) in copies
            push!(lines, declare(slottype(sc, s), sc.names[s]) * ";")
            push!(lines, "memcpy($(sc.names[s]), $(sc.names[p]), sizeof $(sc.names[s]));")
        end
        push!(lines, "")
    end
    append!(lines, body)

    params = [declare(slottype(sc, i), sc.names[i]; constant=isarray(slottype(sc, i)) && !(i in sc.mutated)) for i in 2:ci.nargs]
    if sc.resultparam
        # C can't return an array; it comes out through a trailing parameter, which
        # takes the result's name.
        push!(params, declare(sc.rettype, sc.resultname; restrict=true))
        signature = "void $name($(join(params, ", ")))"
    else
        signature = "$(declare(sc.rettype, name))($(isempty(params) ? "void" : join(params, ", ")))"
    end
    comments, doc = sc.src === nothing ? (String[], String[]) : leading(sc.src)
    origin = "$(mi.def.name)($(join(("$(ci.slotnames[i])::$(widen(ci.slottypes[i]))" for i in 2:ci.nargs), ", ")))" *
             (sc.src === nothing ? "" : ", $(sc.src.name):$(sc.src.first)")
    what(T) = isarray(T) ? describe(T) : T <: Number ? "scalar" : ""
    params = [(i in sc.mutated ? "in,out" : "in", sc.names[i], what(slottype(sc, i))) for i in 2:ci.nargs]
    sc.resultparam && push!(params, ("out", sc.resultname, describe(sc.rettype) * ", the return value"))
    block = doxygen(doc, origin, params)
    return signature * ";", join([comments; block; signature * " {"; [isempty(l) ? l : "    " * l for l in lines]; "}"], "\n") * "\n", sc.names
end

# Everything that has to be known before emission starts: the loops, the statements
# they consume, the values rendered inline, mutated parameters, and slots that are
# only copies of another slot with the same name (a loop variable re-bound for an
# inner loop) — those take the original's name and vanish.
function analyze!(sc::Scope)
    ci = sc.ci
    code = ci.code
    sc.fors = findfors(ci)
    for F in values(sc.fors)
        push!(sc.hidden, F.var)
        for i in F.start:F.bodylo-1; push!(sc.skipped, i); end
        for i in F.next:F.exit-1;    push!(sc.skipped, i); end
        for i in F.machinery;        push!(sc.skipped, i); end
    end
    sc.whiles = findwhiles(ci, sc.fors)
    # Statements consumed by the one that uses them: the pieces of a broadcast, and
    # the tuples that group constructor arguments.
    for (i, st) in enumerate(code)
        st isa Expr && st.head === :call || continue
        f = callee_or_nothing(ci, st.args[1])
        f === Base.broadcasted && push!(sc.skipped, i)
        # A tuple that only feeds a constructor or block construction is compile-time;
        # one that's a value in its own right becomes a struct.
        f === Core.tuple && consumed(ci, i) && push!(sc.skipped, i)
        # The `cconvert`/`unsafe_convert` pair a `ccall` wraps each argument in: no C.
        (f === Base.cconvert || f === Base.unsafe_convert) && push!(sc.skipped, i)
        # A factorization only ever feeds `\` or `inv`; the solver helper does both steps.
        (f === LinearAlgebra.cholesky || f === LinearAlgebra.lu) && push!(sc.skipped, i)
        # A `string(…)` or `repr(…)` that only feeds a print is printed piece by piece.
        (f === Base.string || f === Base.repr) && all(u -> u isa Expr && u.head === :call && callee_or_nothing(ci, u.args[1]) in (Base.print, Base.println, Base.string, Base.repr),
                                                      (u for u in code if uses(u, i))) && push!(sc.skipped, i)
    end
    # The keyword tuple of a `kwcall` — `(dims = 1,)`, built over a few statements — is
    # read at transpile time; none of it is C.
    function skipconstant!(x)
        x isa Core.SSAValue || return
        push!(sc.skipped, x.id)
        code[x.id] isa Expr && foreach(skipconstant!, code[x.id].args)
    end
    for st in code
        st isa Expr && st.head === :call && callee_or_nothing(ci, st.args[1]) === Core.kwcall && skipconstant!(st.args[2])
    end
    # The iterator state of `x, y = t` — `getfield(indexed_iterate(...), 2)`, usually
    # assigned to a hidden slot — has no C.
    for (i, st) in enumerate(code)
        ex = st isa Expr && st.head === :(=) ? st.args[2] : st
        ex isa Expr && ex.head === :call && callee_or_nothing(ci, ex.args[1]) === Core.getfield || continue
        ex.args[3] == 2 && ex.args[2] isa Core.SSAValue && iscall(code[ex.args[2].id], Base.indexed_iterate) || continue
        push!(sc.skipped, i)
        st isa Expr && st.head === :(=) && push!(sc.hidden, st.args[1].id)
    end
    for st in code
        ex = st isa Expr && st.head === :(=) ? st.args[2] : st
        ex isa Expr && ex.head === :call || continue
        f = callee_or_nothing(ci, ex.args[1])
        f in (Base.setindex!, Base.fill!, Base.materialize!) && ex.args[2] isa Core.SlotNumber && push!(sc.mutated, ex.args[2].id)
        # A mutable array handed to a user function that writes somewhere: it may be
        # written there, so it is not `const` here either.
        f isa Function && !(nameof(Base.moduleroot(parentmodule(f))) in known) || continue
        slots = [a.id for a in ex.args[2:end] if a isa Core.SlotNumber && ci.slottypes[a.id] isa Type &&
                 ismutabletype(ci.slottypes[a.id]) && isarray(widen(ci.slottypes[a.id]))]
        isempty(slots) && continue
        r = userinstance!(sc, f, ex.args[2:end])
        r === nothing && continue
        isdisjoint(effects!(sc.prog, r[1]), (:write, :foreign, :unknown)) || push!(sc.mutated, slots...)
    end
    assigned = Dict{Int, Vector{Int}}()
    for (i, st) in enumerate(code)
        st isa Expr && st.head === :(=) && push!(get!(assigned, st.args[1].id, Int[]), i)
    end
    # A parameter that is reassigned: Julia copies it into a fresh slot of the same name
    # at entry and reads that slot from then on. A scalar parameter is by value in C, so
    # the slot simply *is* the parameter, reassigned in place. An array parameter is the
    # caller's memory, so the slot is a working copy, `x_`, made at the top of the
    # function (`cfunction`) — as Julia does, with a comment saying why.
    for (s, at) in assigned
        length(at) >= 2 && s > ci.nargs || continue
        rhs = code[at[1]].args[2]
        rhs isa Core.SSAValue && code[rhs.id] isa Core.SlotNumber && (rhs = code[rhs.id])
        rhs isa Core.SlotNumber && 2 <= rhs.id <= ci.nargs && ci.slotnames[s] == ci.slotnames[rhs.id] || continue
        push!(sc.skipped, at[1])
        if isarray(slottype(sc, s))
            sc.rebound[s] = rhs.id
            push!(sc.declared, s)
        else
            sc.names[s] = sc.names[rhs.id]
            push!(sc.declared, s)   # it is the parameter; nothing to declare
        end
    end
    for (s, at) in assigned
        length(at) == 1 || continue
        rhs = code[at[1]].args[2]
        rhs isa Core.SSAValue && code[rhs.id] isa Core.SlotNumber || continue
        t = code[rhs.id].id
        ci.slotnames[s] == ci.slotnames[t] || continue
        sc.names[s] = sc.names[t]
        push!(sc.hidden, s)
        push!(sc.skipped, at[1])
    end
    markinlined!(sc)
end

callee_or_nothing(ci, x) = try callee(ci, x) catch; nothing end

# Append a line at the current nesting depth.
emit!(lines, sc::Scope, s::AbstractString) = push!(lines, "    "^sc.depth * s)

# Emit `prefix * expr * ";"`, wrapped when it would run past the program's width: the
# expression is split at the operators binding least tightly (outside parentheses and
# strings), and each continuation line starts with an operator, aligned under the
# expression's first operand.
function emitexpr!(lines, sc::Scope, prefix::AbstractString, expr::AbstractString)
    room = sc.prog.width - 4 * (sc.depth + 1)
    length(prefix) + length(expr) + 1 <= room && return emit!(lines, sc, prefix * expr * ";")
    pieces = splitexpr(expr)
    length(pieces) == 1 && return emit!(lines, sc, prefix * expr * ";")
    pad = " " ^ length(prefix)
    line = prefix * pieces[1]
    for k in 2:2:length(pieces)-1
        more = " " * pieces[k] * " " * pieces[k+1]
        if length(line) + length(more) + (k + 1 == length(pieces)) > room
            emit!(lines, sc, line)
            line = pad * pieces[k] * " " * pieces[k+1]
        else
            line *= more
        end
    end
    emit!(lines, sc, line * ";")
end

# The top-level operands of `expr` interleaved with the operators between them, for
# whichever class of operator present binds least tightly: `["a", "+", "b * c", "-", "d"]`.
# Binary operators are rendered with a space on each side; nothing else in an
# expression sits between two spaces.
function splitexpr(expr::AbstractString)
    level = Dict("||" => 1, "&&" => 2, "|" => 3, "^" => 4, "&" => 5, "==" => 6, "!=" => 6, "<" => 7, "<=" => 7, ">" => 7, ">=" => 7,
                 "<<" => 8, ">>" => 8, "+" => 9, "-" => 9, "*" => 10, "/" => 10, "%" => 10)
    c = collect(expr)
    found = Tuple{Int, Int, String}[]     # (level, index of the operator's first character, operator)
    depth, instring, j = 0, false, 1
    while j <= length(c)
        ch = c[j]
        if instring
            ch == '\\' && (j += 1)
            ch == '"' && (instring = false)
        elseif ch == '"'
            instring = true
        elseif ch in "([{"
            depth += 1
        elseif ch in ")]}"
            depth -= 1
        elseif ch == ' ' && depth == 0
            k = something(findnext(==(' '), c, j + 1), length(c) + 1)
            tok = String(c[j+1:k-1])
            haskey(level, tok) && push!(found, (level[tok], j + 1, tok))
        end
        j += 1
    end
    isempty(found) && return [String(expr)]
    lowest = minimum(f[1] for f in found)
    pieces = String[]
    start = 1
    for (l, at, op) in found
        l == lowest || continue
        push!(pieces, String(c[start:at-2]))
        push!(pieces, op)
        start = at + length(op) + 1
    end
    push!(pieces, String(c[start:end]))
    return pieces
end

# Carry the source's comments (and, if asked, code) forward through line `line`, so
# they sit just ahead of the C for the statement on that line.
function annotate!(lines, sc::Scope, line)
    line > sc.cursor || return
    if sc.src !== nothing
        for l in body(sc.src, sc.cursor + 1, line; code=sc.copycode)
            emit!(lines, sc, l)
        end
    end
    sc.cursor = line
end

# A blank line between the C of one Julia statement and the next, so that each
# statement — often several C lines — reads as a paragraph. None right after an
# opening brace; `cfunction` removes any left against a closing one.
separate!(lines, sc::Scope) = isempty(lines) || isempty(last(lines)) || endswith(last(lines), "{") || push!(lines, "")

# The type of a slot, shaped if it holds an array.
slottype(sc::Scope, i) = get(sc.slotshapes, i, widen(sc.ci.slottypes[i]))

# Emit the C for one IR statement, appending to `lines`.
function statement!(lines, sc::Scope, i, st)
    ci = sc.ci
    sc.current = i
    st === nothing && return
    st isa GlobalRef && return                    # constant load; resolved where it's used
    st isa Core.NewvarNode && return
    st isa Expr && st.head in (:meta, :code_coverage_effect) && return
    i in sc.inlined && return                     # rendered inside the expression that consumes it
    T = widen(ci.ssavaluetypes[i])
    T === Union{} && return                       # unreachable
    if st isa Core.ReturnNode
        if valuetype(sc, st.val) === Nothing
            i == length(ci.code) || emit!(lines, sc, "return;")
            return
        end
        v = value(sc, st.val)
        if sc.resultparam
            # An array result is written into the out parameter; if it isn't there
            # already, copy it. The result has Julia's return type where that has a
            # size, otherwise the value's own; a transposed value landing in a plain
            # type is copied with its axes swapped. A `return` is only needed before
            # the end.
            shape(sc.rettype) === nothing && (sc.rettype = valuetype(sc, st.val))
            v == sc.resultname || copy!(lines, sc, v, valuetype(sc, st.val), sc.resultname, sc.rettype)
            i == length(ci.code) || emit!(lines, sc, "return;")
        else
            emitexpr!(lines, sc, "return ", v)
        end
    elseif st isa Expr && st.head === :foreigncall
        code = foreign!(sc, st)
        if T === Nothing
            emit!(lines, sc, code * ";")
        else
            name = onlyreturned(ci, i) ? result!(sc, i) : temp!(sc, i, parts(sc, foreignargs(sc, st)))
            emit!(lines, sc, "$(ctype(T)) $name = $code;")
        end
    elseif st isa Expr && st.head === :call && callee_or_nothing(ci, st.args[1]) in (Base.print, Base.println)
        print!(lines, sc, st.args[2:end], callee(ci, st.args[1]) === Base.println)
    elseif st isa Expr && st.head === :call && callee_or_nothing(ci, st.args[1]) === Printf.format && !(T <: AbstractString)
        printf!(lines, sc, st.args[2:end])
    elseif st isa Expr && st.head === :call && callee_or_nothing(ci, st.args[1]) in (Base.fill!, Base.materialize!)
        inplace!(lines, sc, i, st)
    elseif st isa Expr && st.head === :call && (T === Nothing || T === Any) && userinstance!(sc, callee_or_nothing(ci, st.args[1]), st.args[2:end]) !== nothing
        # A call for its effect, or whose result goes unused (Julia then types it `Any`
        # and the callee's own return type says what C needs).
        mi, _, name = userinstance!(sc, callee(ci, st.args[1]), st.args[2:end])
        R = returntype(mi)
        if isarray(R)
            t = temp!(sc, i, parts(sc, st))
            emit!(lines, sc, declare(R, t) * ";")
            emit!(lines, sc, "$name($(callargs(sc, st.args[2:end])), $t);")
        else
            emit!(lines, sc, "$name($(callargs(sc, st.args[2:end])));")
        end
    elseif st isa Expr && st.head === :call && (callee_or_nothing(ci, st.args[1]) === Core.tuple || (callee_or_nothing(ci, st.args[1]) isa Type && isstruct(T)))
        # A tuple or struct value: `(Point){x, y}`, or field by field when a field is an array.
        dest = onlyreturned(ci, i) ? result!(sc, i) : temp!(sc, i, parts(sc, st))
        compound!(lines, sc, i, T, st.args[2:end], dest; declared=false)
    elseif st isa Expr && st.head === :call && callee_or_nothing(ci, st.args[1]) === Base.indexed_iterate
        # `x, y = t`: the k-th field, as the value; the iterator state is compile-time.
        t, k = st.args[2], st.args[3]
        sc.expr[i] = fieldaccess(sc, t, k)
        isarray(T) && (sc.shapes[i] = widen(ci.ssavaluetypes[i]).parameters[1])
    elseif st isa Expr && st.head === :call && callee_or_nothing(ci, st.args[1]) in (Base.getproperty, Core.getfield, Base.getindex) && !isarray(valuetype(sc, st.args[2])) && (isstruct(valuetype(sc, st.args[2])) || istuple(valuetype(sc, st.args[2])) || isindexediterate(sc, st.args[2]))
        # A field read is just a name: no temp.
        sc.expr[i] = isindexediterate(sc, st.args[2]) ? value(sc, st.args[2]) : fieldaccess(sc, st.args[2], st.args[3])
        isarray(T) && (sc.shapes[i] = T)
    elseif st isa Expr && st.head === :call
        f = callee_or_nothing(ci, st.args[1])
        if f === Base.setproperty! || f === Base.setfield!
            S = valuetype(sc, st.args[2])
            F = fieldtype(S, literal(sc, st.args[3]))
            target = fieldaccess(sc, st.args[2], st.args[3])
            isarray(F) ? copy!(lines, sc, value(sc, st.args[4]), valuetype(sc, st.args[4]), target, F) :
                         emit!(lines, sc, "$target = $(value(sc, st.args[4]));")
        elseif f === Base.setindex! && any(k -> literal(sc, k) isa Colon || literal(sc, k) isa AbstractUnitRange, st.args[4:end])
            setslice!(lines, sc, i, st.args[2], st.args[3], st.args[4:end])
        elseif f === Base.setindex!
            emit!(lines, sc, "$(index(sc, st.args[2], st.args[4:end])) = $(value(sc, st.args[3]));")
        elseif f in (Base.zeros, Base.ones, Base.fill) || (f in (Base.zero, Base.one) && isarray(T)) || isconstruction(f) || f === Base.materialize
            dest = onlyreturned(ci, i) ? result!(sc, i) : temp!(sc, i, parts(sc, st))
            construct!(lines, sc, i, st, dest; declaration=!(onlyreturned(ci, i) && sc.resultparam))
        elseif (f === Base.adjoint || f === Base.transpose) && isarray(T)
            # A transpose is the same storage with its axes read the other way round:
            # nothing to do in C, the value just carries the tag from here on.
            sc.expr[i] = value(sc, st.args[2])
            sc.shapes[i] = transposed(valuetype(sc, st.args[2]))
        elseif f in (Base.lastindex, Base.firstindex, Base.length, Base.size) && ci.ssavaluetypes[i] isa Core.Const && ci.ssavaluetypes[i].val isa Integer
            # A size inference already knows (`end` in an index): the number, no temp.
            sc.expr[i] = string(ci.ssavaluetypes[i].val)
        elseif f === Colon() || f === Base.OneTo || f === Base.eachindex || f === Base.axes
            # A literal range that only indexes (`v[2:3]`) is compile-time; any other
            # range outside a `for` has no C.
            ci.ssavaluetypes[i] isa Core.Const && all(st -> iscall(st, Base.getindex) || iscall(st, Base.setindex!), (st for st in ci.code if uses(st, i))) && return
            throw(ArgumentError("ranges are only supported as the range of a for loop (statement $i)"))
        elseif isarray(T) && foldable(sc, i, st)
            # `-x` feeding `x * s` or `x / s`: the sign goes onto the scalar, exactly.
            push!(sc.negated, i)
            sc.expr[i] = value(sc, st.args[2])
            sc.shapes[i] = valuetype(sc, st.args[2])
        elseif isarray(T)
            # A calculation whose only use is to be returned is the function's result.
            if onlyreturned(ci, i)
                dest = result!(sc, i)
                arraycall!(lines, sc, i, st, dest; declaration=!sc.resultparam)
            else
                arraycall!(lines, sc, i, st, temp!(sc, i, parts(sc, st)); declaration=true)
            end
        elseif compiletime(ci.ssavaluetypes[i])
            return                                # a type or Val: no C meaning
        else
            code, _ = render(sc, i, st)
            name = onlyreturned(ci, i) ? result!(sc, i) : temp!(sc, i, parts(sc, st))
            emitexpr!(lines, sc, "$(ctype(T)) $name = ", code)
            haskey(sc.math, i) && step!(lines, sc, "$name = $(sc.math[i])")
        end
    elseif st isa Expr && st.head === :(=)
        # `%i = (x = rhs)`: the SSA value is the value assigned. Refer to it as `x`
        # where that's safe; otherwise keep a temp copy.
        slot, rhs = st.args
        if slot.id in sc.hidden
            # A slot Julia left unnamed that really holds a value — the result of a
            # `c ? x : y` used as a value — is a local like any other, named as a temp.
            delete!(sc.hidden, slot.id)
            sc.names[slot.id] = temp!(sc, nothing, String[])
        end
        x = sc.names[slot.id]
        # A variable is declared at its first assignment. Inside an `if` or a loop that
        # would scope it to the block, so there it is declared just before the construct.
        fresh = !(slot.id in sc.declared) && !(slot.id in sc.hidden)
        fresh && push!(sc.declared, slot.id)
        here = fresh && sc.depth == 0
        if isarray(T)
            store!(lines, sc, i, x, rhs; declaration=here)
        elseif rhs isa Expr && rhs.head === :call && (callee_or_nothing(ci, rhs.args[1]) === Core.tuple || (callee_or_nothing(ci, rhs.args[1]) isa Type && isstruct(T)))
            compound!(lines, sc, i, T, rhs.args[2:end], x; declared=!here)
        else
            emitexpr!(lines, sc, (here ? ctype(T) * " " : "") * "$x = ", rhs isa Expr ? first(render(sc, i, rhs)) : value(sc, rhs))
        end
        if fresh && !here
            s = slot.id
            push!(sc.inserts, (sc.blockstart, 0, () -> declare(slottype(sc, s), x) * ";"))
        end
        if stable(ci, i, slot.id)
            sc.expr[i] = x
            # The value just stored is now also `x`; if it was a temp, later uses
            # (typically the return) can say `x` instead.
            rhs isa Core.SSAValue && !(rhs.id in sc.inlined) && (sc.expr[rhs.id] = x)
        else
            t = temp!(sc, i, contribution(sc, slot))
            emit!(lines, sc, isarray(T) ? "$(declare(valuetype(sc, slot), t));" : "$(ctype(T)) $t = $x;")
            isarray(T) && copy!(lines, sc, x, valuetype(sc, slot), t, valuetype(sc, slot))
        end
        isarray(T) && (sc.shapes[i] = valuetype(sc, slot))
    elseif st isa Core.SlotNumber
        # `%i = x`: a read of a variable. Same rule as above.
        x = sc.names[st.id]
        if stable(ci, i, st.id)
            sc.expr[i] = x
        else
            t = temp!(sc, i, contribution(sc, st))
            emit!(lines, sc, isarray(T) ? "$(declare(valuetype(sc, st), t));" : "$(ctype(T)) $t = $x;")
            isarray(T) && copy!(lines, sc, x, valuetype(sc, st), t, valuetype(sc, st))
        end
        isarray(T) && (sc.shapes[i] = valuetype(sc, st))
    elseif st isa Core.SSAValue || st isa Number
        sc.expr[i] = value(sc, st)                 # pure copy; no temp needed
        isarray(T) && (sc.shapes[i] = valuetype(sc, st))
    elseif st isa Core.GotoIfNot || st isa Core.GotoNode
        throw(ArgumentError("control flow not recognised at statement $i"))
    else
        throw(ArgumentError("unsupported statement: $st"))
    end
end

# A statement whose value is a type, a `Val`, or a tuple: compile-time only.
compiletime(t) = t isa Core.Const && !(t.val isa Number) && !(t.val isa AbstractArray)

# Emit `x = rhs` for an array `x`: a helper writing straight into `x` when `x` isn't
# also an operand, otherwise through a temp so the operation can't read what it's
# overwriting.
function store!(lines, sc::Scope, i, x, rhs; declaration::Bool=false)
    slot = sc.ci.code[i].args[1].id
    # With `declaration`, `x` is declared here, at its first assignment: by the emitter
    # that writes it when there is one, otherwise just before the copy into it.
    if rhs isa Expr
        f = callee_or_nothing(sc.ci, rhs.args[1])
        making = f in (Base.zeros, Base.ones, Base.fill, Base.zero, Base.one) || isconstruction(f) || f === Base.materialize
        if f in (Core.getfield, Base.getproperty, Base.getindex) && (isindexediterate(sc, rhs.args[2]) || isstruct(valuetype(sc, rhs.args[2])) || istuple(valuetype(sc, rhs.args[2])))
            # An array field of a struct or tuple, copied out: `copy_3(t.a, p);`.
            T = slottype(sc, slot)
            src = isindexediterate(sc, rhs.args[2]) ? value(sc, rhs.args[2]) : fieldaccess(sc, rhs.args[2], rhs.args[3])
            declaration && emit!(lines, sc, declare(T, x) * ";")
            copy!(lines, sc, src, T, x, T)
            sc.shapes[i] = T
        elseif (f === Base.adjoint || f === Base.transpose) && isarray(valuetype(sc, rhs.args[2]))
            # `B = A'`: a copy into whatever Julia says `B` is. A lazy `Adjoint` (a
            # vector's) is the same storage, known to be transposed; an eager one
            # (StaticArrays materializes a matrix transpose) is copied axes-swapped.
            A = transposed(valuetype(sc, rhs.args[2]))
            R = slottype(sc, slot)
            shape(R) === nothing && (R = A)
            declaration && emit!(lines, sc, declare(R, x) * ";")
            start = length(lines) + 1
            copy!(lines, sc, value(sc, rhs.args[2]), A, x, R)
            step!(lines, sc, "$x = $(value(sc, rhs.args[2]))ᵀ"; from=start)
            sc.shapes[i] = R
        elseif any(a -> mentions(sc, x, a), rhs.args[2:end]) && !inplace(sc, rhs, slottype(sc, slot))
            # `x` is also an operand of something that reads elements it has already
            # written — a product, a solve, a transpose, a construction: through a temp.
            t = temp!(sc, nothing, parts(sc, rhs))
            making ? construct!(lines, sc, i, rhs, t; declaration=true) : arraycall!(lines, sc, i, rhs, t; declaration=true)
            declaration && emit!(lines, sc, declare(valuetype(sc, Core.SSAValue(i)), x) * ";")
            copy!(lines, sc, t, valuetype(sc, Core.SSAValue(i)), x, valuetype(sc, Core.SSAValue(i)))
        elseif making
            construct!(lines, sc, i, rhs, x; declaration)
        else
            arraycall!(lines, sc, i, rhs, x; declaration)
        end
        sc.slotshapes[slot] = sc.shapes[i]
    else
        declaration && emit!(lines, sc, declare(valuetype(sc, rhs), x) * ";")
        copy!(lines, sc, value(sc, rhs), valuetype(sc, rhs), x, valuetype(sc, rhs))
        sc.slotshapes[slot] = valuetype(sc, rhs)
    end
end

# Calls that make a whole array: `zeros`/`ones`/`fill`, `zero`/`one`, `SMatrix{…}(I)`,
# block construction and array literals, static constructors, and a broadcast being
# materialized.
function construct!(lines, sc::Scope, i, ex::Expr, dest; declaration::Bool=false)
    f = callee(sc.ci, ex.args[1])
    args = ex.args[2:end]
    f === Base.materialize && return broadcast!(lines, sc, i, args[1], dest; declaration)
    T = widen(sc.ci.ssavaluetypes[i])
    if isconstruction(f) && length(args) == 1 && literal(sc, args[1]) isa LinearAlgebra.UniformScaling
        # `SMatrix{3,3}(I)`, `SMatrix{3,3}(2I)`: the identity matrix, or a multiple of it.
        λ = literal(sc, args[1]).λ
        declaration && emit!(lines, sc, declare(T, dest) * ";")
        start = length(lines) + 1
        identity!(lines, sc, dest, T; diagonal=λ == 1 ? nothing : value(sc, eltype(T)(λ)))
        step!(lines, sc, "$dest = $(λ == 1 ? "" : value(sc, λ))I"; from=start)
        sc.shapes[i] = T
        return
    end
    isconstruction(f) && return concatenate!(lines, sc, i, f, args, dest; declaration)
    if f in (Base.zero, Base.one) || (f in (Base.zeros, Base.ones) && length(args) == 1 && literal(sc, args[1]) isa Type) ||
       (f === Base.fill && length(args) == 2 && literal(sc, args[2]) isa Type)
        # `zero(A)`, `zeros(SMatrix{3,4})`, `one(A)`, `fill(x, SMatrix{2,2})`: the size is in
        # the result's type.
        shape(T) === nothing && throw(ArgumentError("$f needs a static array type (statement $i)"))
        declaration && emit!(lines, sc, declare(T, dest) * ";")
        x = f === Base.fill ? value(sc, args[1]) : eltype(T) <: AbstractFloat ? "1.0" : "1"
        start = length(lines) + 1
        f === Base.one ? identity!(lines, sc, dest, T) :
        f in (Base.zero, Base.zeros) ? zero!(lines, sc, dest, T) :
        fill!(lines, sc, dest, T, x)
        step!(lines, sc, f === Base.one ? "$dest = I" : f in (Base.zero, Base.zeros) ? "$dest .= 0" : "$dest .= $x"; from=start)
        sc.shapes[i] = T
        return
    end
    x = f === Base.fill ? value(sc, args[1]) : "1.0"
    f === Base.fill && (args = args[2:end])
    dims = [literal(sc, a) isa Integer ? literal(sc, a) : throw(ArgumentError("$f needs literal dimensions (statement $i)")) for a in args]
    R = shaped(eltype(T), Tuple(dims))
    eltype(T) <: AbstractFloat || f !== Base.ones || (x = "1")
    declaration && emit!(lines, sc, declare(R, dest) * ";")
    start = length(lines) + 1
    f === Base.zeros ? zero!(lines, sc, dest, R) : fill!(lines, sc, dest, R, x)
    step!(lines, sc, f === Base.zeros ? "$dest .= 0" : "$dest .= $x"; from=start)
    sc.shapes[i] = R
end

# The compile-time value of `x`, or `nothing` if it has none.
function literal(sc::Scope, x)
    x isa QuoteNode && return x.value
    x isa Core.SSAValue && return (t = sc.ci.ssavaluetypes[x.id]; t isa Core.Const ? t.val : nothing)
    x isa GlobalRef && return getfield(x.mod, x.name)
    return x
end

# `hvcat`, `vcat`, `hcat`, `vect`, their `typed_` forms, and static-array constructors.
isconstruction(f) = f in (Base.hvcat, Base.vcat, Base.hcat, Base.vect, Base.typed_hvcat, Base.typed_vcat, Base.typed_hcat, Base.hvncat) ||
                    (f isa Type && f <: StaticArrays.StaticArray)

# Block construction and array literals. All-scalar literals are assigned element by
# element; anything with an array block goes through a `cat` helper.
function concatenate!(lines, sc::Scope, i, f, args, dest; declaration::Bool=false)
    ci = sc.ci
    tupleof(x) = x isa Core.SSAValue && iscall(ci.code[x.id], Core.tuple) ? ci.code[x.id].args[2:end] :
                 x isa Core.SSAValue && ci.ssavaluetypes[x.id] isa Core.Const ? collect(ci.ssavaluetypes[x.id].val) : nothing
    if f isa Type
        # `SVector(a, b, c)`, `SMatrix{2,2}(t)`: elements in column-major order.
        elems = length(args) == 1 && tupleof(args[1]) !== nothing ? tupleof(args[1]) : args
        R = widen(ci.ssavaluetypes[i])
        all(a -> !isarray(valuetype(sc, a)), elems) || throw(ArgumentError("a static constructor from arrays is not supported (statement $i)"))
        declaration && emit!(lines, sc, declare(R, dest) * ";")
        s = shape(R)
        # Elements arrive column-major; write them row by row, as a person would.
        order = length(s) == 1 ? eachindex(elems) : sort(eachindex(elems); by=k -> ((k - 1) % s[1], (k - 1) ÷ s[1]))
        for k in order
            sub = length(s) == 1 ? "[$(k-1)]" : "[$((k-1) % s[1])][$((k-1) ÷ s[1])]"
            emit!(lines, sc, "$dest$sub = $(value(sc, elems[k]));")
        end
        sc.shapes[i] = R
        return
    end
    f in (Base.typed_hvcat, Base.typed_vcat, Base.typed_hcat) && (args = args[2:end])
    # Every form is a tree of concatenations (see `layout` in move.jl).
    if f in (Base.hvcat, Base.typed_hvcat)
        rows = tupleof(args[1])
        rows === nothing && throw(ArgumentError("hvcat needs literal row lengths (statement $i)"))
        blocks = args[2:end]
        starts = cumsum([1; rows[1:end-1]])
        tree = (1, Any[(2, Any[k:k+n-1...]) for (k, n) in zip(starts, rows)])
    elseif f === Base.hvncat && literal(sc, args[1]) isa Tuple
        blocks = args[3:end]
        tree = grouped(literal(sc, args[1]), literal(sc, args[2]) === true, 1:length(blocks))
    elseif f === Base.hvncat
        d = literal(sc, args[1])
        d isa Integer && d >= 1 || throw(ArgumentError("concatenation needs a literal dimension (statement $i)"))
        blocks = args[2:end]
        tree = (d, Any[1:length(blocks)...])
    else
        blocks = args
        tree = (f in (Base.vcat, Base.typed_vcat, Base.vect) ? 1 : 2, Any[1:length(blocks)...])
    end
    types = [valuetype(sc, b) for b in blocks]
    size, _ = layout(tree, types)
    T = widen(ci.ssavaluetypes[i])
    E = eltype(T)
    R = shape(T) !== nothing ? T : shaped(E, Tuple(ndims(T) == 1 ? size[1:1] : size))
    ndims(R) == 1 && any(!=(1), size[2:end]) && throw(ArgumentError("a vector can't hold $(join(size, "×")) (statement $i)"))
    declaration && emit!(lines, sc, declare(R, dest) * ";")
    start = length(lines) + 1
    construct!(lines, sc, tree, blocks, dest, R)
    step!(lines, sc, "$dest = $(catnotation(sc, tree, blocks, f))"; from=start)
    sc.shapes[i] = R
end

# A block construction in Julia's bracket notation, with the C names: `[A B; C D]` for
# the `hvcat` family, the `;;` form for `hvncat`.
function catnotation(sc::Scope, tree, blocks, f)
    hv = f === Base.hvncat
    text(node) = node isa Integer ? spell(valuetype(sc, blocks[node]), value(sc, blocks[node])) :
                 join((text(c) for c in node[2]), hv ? ";"^node[1] * " " : node[1] == 1 ? "; " : " ")
    return "[" * text(tree) * "]"
end

# A broadcast tree, from its `broadcasted` root, into `dest`. Julia fuses nested
# broadcasts into one loop; here each level is its own helper, chained through temps.
function broadcast!(lines, sc::Scope, i, root, dest; declaration::Bool=false)
    ci = sc.ci
    node = ci.code[root.id]                       # broadcasted(f, args...)
    f = callee(ci, node.args[2])
    args = node.args[3:end]
    # Inner broadcasts first, each into a temp.
    inputs = Any[]
    for a in args
        if a isa Core.SSAValue && iscall(ci.code[a.id], Base.broadcasted)
            t = temp!(sc, a.id, parts(sc, ci.code[a.id]))
            broadcast!(lines, sc, a.id, a, t; declaration=true)
            push!(inputs, Core.SSAValue(a.id))
        else
            push!(inputs, a)
        end
    end
    types = [valuetype(sc, a) for a in inputs]
    any(isarray, types) || throw(ArgumentError("a broadcast over scalars only (statement $i)"))
    bs = broadcastshape(types)
    bs === nothing && throw(ArgumentError("broadcast: shapes don't line up: $(join(dims.(filter(isarray, types)), ", "))"))
    T = widen(ci.ssavaluetypes[i])
    if isarray(T)
        E = eltype(T)
        R = shape(T) !== nothing ? T :
            T <: LinearAlgebra.Adjoint || T <: LinearAlgebra.Transpose ? Transposed{E, Tuple(reverse(bs)[1:ndims(T)]), ndims(T)} : shaped(E, bs)
    else
        # An inner node of a fused broadcast: the IR only knows it as a `Broadcasted`.
        E = promote_type((isarray(t) ? eltype(t) : t for t in types)...)
        R = all(t -> !isarray(t) || istransposed(t), types) ?
            (nd = maximum(ndims(t) for t in types if isarray(t)); Transposed{E, Tuple(reverse(bs)[1:nd]), nd}) : shaped(E, bs)
    end
    op, cfn = broadcastop(f, length(inputs), E)
    cfn isa String && push!(sc.headers, cfn == "llabs" ? "stdlib.h" : "math.h")
    cfn isa String && cfn != "llabs" && E === Float32 && (cfn *= "f")   # the `f` family on floats
    declaration && emit!(lines, sc, declare(R, dest) * ";")
    name = broadcasthelper!(sc.helpers, op, cfn, types, R)
    emit!(lines, sc, "$name($(join((value(sc, a) for a in inputs), ", ")), $dest);")
    spelled = [spell(valuetype(sc, a), value(sc, a)) for a in inputs]
    step!(lines, sc, "$dest = " * (length(inputs) == 1 ? (cfn == :neg ? ".-$(spelled[1])" : cfn == :not ? ".!$(spelled[1])" : "$op.($(spelled[1]))") :
                                    length(inputs) == 2 && haskey(dotspelling, op) ? "$(spelled[1]) $(dotspelling[op]) $(spelled[2])" : "$op.($(join(spelled, ", ")))"))
    sc.shapes[i] = R
end

# The helper name and C form of a broadcast's function.
function broadcastop(f, n, E)
    for (g, op) in ((Base.:<, :lt), (Base.:<=, :le), (Base.:>, :gt), (Base.:>=, :ge), (Base.:(==), :eq), (Base.:!=, :ne),
                    (Base.:&, :and), (Base.:|, :or), (Base.:!, :not), (Base.ifelse, :ifelse))
        f === g && return op, op
    end
    f === Base.:+ && return :add, :add
    f === Base.:- && return n == 1 ? (:neg, :neg) : (:sub, :sub)
    f === Base.:* && return :mul, :mul
    f === Base.:/ && return :div, :div
    f === Base.:^ && return :pow, "pow"
    f === Base.abs && return :abs, E <: AbstractFloat ? "fabs" : "llabs"
    f === Base.max && return :max, "fmax"
    f === Base.min && return :min, "fmin"
    for (g, name) in ((Base.sqrt, "sqrt"), (Base.cbrt, "cbrt"), (Base.sin, "sin"), (Base.cos, "cos"), (Base.tan, "tan"),
                      (Base.asin, "asin"), (Base.acos, "acos"), (Base.atan, "atan"), (Base.sinh, "sinh"), (Base.cosh, "cosh"),
                      (Base.tanh, "tanh"), (Base.exp, "exp"), (Base.exp2, "exp2"), (Base.expm1, "expm1"), (Base.log, "log"),
                      (Base.log2, "log2"), (Base.log10, "log10"), (Base.log1p, "log1p"), (Base.floor, "floor"),
                      (Base.ceil, "ceil"), (Base.trunc, "trunc"), (Base.round, "rint"))
        f === g && return Symbol(name == "rint" ? "round" : name), name
    end
    throw(ArgumentError("unsupported broadcast function: $f"))
end

# Emit the helper call for an array operation, writing into `dest`. An n-ary `+` or `*`
# (Julia parses `A + B + C` as one call) is chained through temps.
function arraycall!(lines, sc::Scope, i, ex::Expr, dest; declaration::Bool=false)
    f = callee(sc.ci, ex.args[1])
    args = ex.args[2:end]
    E = eltype(widen(sc.ci.ssavaluetypes[i]))
    if f === LinearAlgebra.cross
        types = (valuetype(sc, args[1]), valuetype(sc, args[2]))
        R = retype(types[1], E)
        declaration && emit!(lines, sc, declare(R, dest) * ";")
        emit!(lines, sc, "$(crosshelper!(sc.helpers, types, R))($(value(sc, args[1])), $(value(sc, args[2])), $dest);")
        step!(lines, sc, "$dest = $(value(sc, args[1])) × $(value(sc, args[2]))")
        sc.shapes[i] = R
        return
    end
    f === Base.getindex && return slice!(lines, sc, i, args, dest; declaration)
    if f === Base.copy
        R = valuetype(sc, args[1])
        declaration && emit!(lines, sc, declare(R, dest) * ";")
        start = length(lines) + 1
        copy!(lines, sc, value(sc, args[1]), R, dest, R)
        step!(lines, sc, "$dest = $(value(sc, args[1]))"; from=start)
        sc.shapes[i] = R
        return
    end
    # `s \ A` is `A / s`; `A / s` is elementwise; anything else with `\` or `/` is a solve.
    f === Base.:\ && valuetype(sc, args[1]) <: Number && (args = [args[2], args[1]]; f = Base.:/)
    (f === Base.:\ || f === Base.inv || f === LinearAlgebra.pinv || (f === Base.:/ && isarray(valuetype(sc, args[2])))) && return solve!(lines, sc, i, f, args, dest; declaration)
    name = usercall!(sc, f, args)
    if name !== nothing
        R = widen(sc.ci.ssavaluetypes[i])
        declaration && emit!(lines, sc, declare(R, dest) * ";")
        emit!(lines, sc, "$name($(callargs(sc, args)), $dest);")
        step!(lines, sc, "$dest = $name($(callargs(sc, args)))")
        sc.shapes[i] = R
        return
    end
    # `sum(A; dims=1)`, `diff(v)`, `cumsum(A; dims=2)`: an operation along one dimension.
    if f === Core.kwcall || f in (Base.diff, Base.cumsum, Base.cumprod)
        kw = f === Core.kwcall ? literal(sc, args[1]) : (;)
        f === Core.kwcall && (f = callee(sc.ci, args[2]); args = args[3:end])
        return along!(lines, sc, i, f, args, kw, dest; declaration)
    end
    op = f === Base.:+ ? :add :
         f === Base.:- ? (length(args) == 1 ? :neg : :sub) :
         f === Base.:* ? :mul :
         f === Base.:/ ? :div :
         throw(ArgumentError("unsupported array operation: $f"))
    # `A + 2I`, `A - I`, `2I - A`: a multiple of the identity on the diagonal.
    op in (:add, :sub) && length(args) == 2 && any(a -> literal(sc, a) isa LinearAlgebra.UniformScaling, args) &&
        return scaling!(lines, sc, i, op, args, dest; declaration)
    # The result's element type comes from Julia's promotion; its size from the IR if
    # the type carries one, otherwise from the operation's own rule.
    result(types) = (R = widen(sc.ci.ssavaluetypes[i]); shape(R) === nothing ? resulttype(op, types, E) : R)
    # An integer literal coefficient of a floating array takes the array's element type:
    # `-3A` is `mul_s_2x2(-3.0, A, out)`, not a mixed-type helper and an `int64_t`.
    function operand(x, other)
        x isa Integer && isarray(other) && eltype(other) <: AbstractFloat && return eltype(other), value(sc, eltype(other)(x))
        return valuetype(sc, x), value(sc, x)
    end
    acc = args[1]
    acctype, accname = length(args) >= 2 ? operand(acc, valuetype(sc, args[2])) : (valuetype(sc, acc), value(sc, acc))
    R = acctype
    for (n, a) in enumerate(args[2:end])
        last = n == length(args) - 1
        atype, aname = operand(a, acctype)
        types = (acctype, atype)
        R = result(types)
        out = last ? dest : temp!(sc, nothing, unique([contribution(sc, acc); contribution(sc, a)]))
        (last ? declaration : true) && emit!(lines, sc, declare(R, out) * ";")
        # A folded negation (`foldable`) lands on the scalar operand.
        isnegated(sc, acc) && (aname = negate(aname))
        isnegated(sc, a) && (accname = negate(accname))
        emit!(lines, sc, "$(helper!(sc.helpers, op, types, R))($accname, $aname, $out);")
        step!(lines, sc, "$out = $(spell(acctype, accname)) $(Dict(:add => "+", :sub => "-", :mul => "*", :div => "/")[op]) $(spell(atype, aname))")
        accname, acctype = out, R
    end
    if length(args) == 1
        R = result((acctype,))
        declaration && emit!(lines, sc, declare(R, dest) * ";")
        emit!(lines, sc, "$(helper!(sc.helpers, op, (acctype,), R))($accname, $dest);")
        step!(lines, sc, "$dest = -$(spell(acctype, accname))")
    end
    sc.shapes[i] = R
end

# `A \ b`, `inv(A)`, and the same through `cholesky(A)` or `lu(A)`: one helper each,
# with the factorization inside it. Sizes 1–3 are written out; from 4 on it's LU with
# partial pivoting or Cholesky, which can fail on a singular or non-positive-definite
# matrix — that prints Julia's exception and stops, so the output needs `stdio.h` and
# `stdlib.h`.
function solve!(lines, sc::Scope, i, f, args, dest; declaration::Bool=false)
    ci = sc.ci
    x = args[1]
    method = :lu
    if x isa Core.SSAValue && ci.code[x.id] isa Expr && ci.code[x.id].head === :call
        g = callee_or_nothing(ci, ci.code[x.id].args[1])
        if g === LinearAlgebra.cholesky || g === LinearAlgebra.lu
            method = g === LinearAlgebra.cholesky ? :llt : :lu
            x = ci.code[x.id].args[2]
        end
    end
    if f === Base.:/
        # `B / A`: every row of `B` against `Aᵀ`.
        B, A = valuetype(sc, args[1]), valuetype(sc, args[2])
        R = widen(ci.ssavaluetypes[i])
        shape(A)[1] >= 4 && union!(sc.headers, ("stdio.h", "stdlib.h", "math.h"))
        declaration && emit!(lines, sc, declare(R, dest) * ";")
        emit!(lines, sc, "$(rsolvehelper!(sc.helpers, B, A, R))($(value(sc, args[1])), $(value(sc, args[2])), $dest);")
        step!(lines, sc, "$dest = $(spell(B, value(sc, args[1]))) / $(spell(A, value(sc, args[2])))")
        sc.shapes[i] = R
        return
    end
    T = valuetype(sc, x)
    R = widen(ci.ssavaluetypes[i])
    n = shape(T)[1]
    (n >= 4 || method == :llt || f === LinearAlgebra.pinv || !allequal(shape(T))) && union!(sc.headers, ("stdio.h", "stdlib.h", "math.h"))
    if f === LinearAlgebra.pinv
        declaration && emit!(lines, sc, declare(R, dest) * ";")
        emit!(lines, sc, "$(pinvhelper!(sc.helpers, T, R))($(value(sc, x)), $dest);")
        step!(lines, sc, "$dest = pinv($(spell(T, value(sc, x))))")
        sc.shapes[i] = R
        return
    end
    if f === Base.inv
        name = method == :llt ? invLLThelper!(sc.helpers, T, R) : invhelper!(sc.helpers, T, R)
        declaration && emit!(lines, sc, declare(R, dest) * ";")
        emit!(lines, sc, "$name($(value(sc, x)), $dest);")
        step!(lines, sc, "$dest = $(spell(T, value(sc, x)))⁻¹")
    else
        B = valuetype(sc, args[2])
        name = method == :llt ? solveLLThelper!(sc.helpers, T, B, R) : solvehelper!(sc.helpers, T, B, R)
        declaration && emit!(lines, sc, declare(R, dest) * ";")
        emit!(lines, sc, "$name($(value(sc, x)), $(value(sc, args[2])), $dest);")
        step!(lines, sc, "$dest = $(spell(T, value(sc, x))) \\ $(spell(B, value(sc, args[2])))")
    end
    sc.shapes[i] = R
end

# `A[i, :]`, `A[:, j]`, `v[2:4]`, `A[1:2, 2:3]`, `A[i, 2:3]`: a copy of part of an array,
# in any dimension, written inline into `dest`. Each index is a scalar (that dimension
# is dropped), a colon, or a literal range.
function slice!(lines, sc::Scope, i, args, dest; declaration::Bool=false)
    A, idx = args[1], args[2:end]
    T = valuetype(sc, A)
    length(idx) == ndims(T) || throw(ArgumentError("$(length(idx)) indices into a $(ndims(T))-dimensional array (statement $i)"))
    spans = [span(sc, T, d, k) for (d, k) in enumerate(idx)]
    R = widen(sc.ci.ssavaluetypes[i])
    shape(R) === nothing && (R = shaped(eltype(T), Tuple(s.extent for s in spans if !s.scalar)))
    declaration && emit!(lines, sc, declare(R, dest) * ";")
    start = length(lines) + 1
    slice!(lines, sc, value(sc, A), T, spans, dest, R)
    step!(lines, sc, "$dest = $(value(sc, A))[$(join((indexnotation(sc, k) for k in idx), ", "))]"; from=start)
    sc.shapes[i] = R
end

# One index as the Julia wrote it — `:`, `2:3`, or the expression — for a step comment.
function indexnotation(sc::Scope, k)
    x = literal(sc, k)
    x isa Colon && return ":"
    x isa AbstractUnitRange && return "$(first(x)):$(last(x))"
    k isa Integer && return string(k)
    return first(expression(sc, k))
end

# One index of a slice, as the 0-based C offset it starts at and the extent it covers
# along dimension `d` of `T`: a scalar covers 1, a colon the whole dimension, a literal
# range its length.
function span(sc::Scope, T::Type, d, k)
    x = literal(sc, k)
    x isa Colon && return (offset="0", extent=extent(T, d), scalar=false)
    x isa AbstractUnitRange && return (offset=string(first(x) - 1), extent=length(x), scalar=false)
    return (offset=zerobased(sc, k), extent=1, scalar=true)
end

# `A[2, :] = v`, `A[:, 3:4] = B`, `v[2:3] = w`: part of a mutable array assigned from a
# whole array, written inline. Julia requires the shapes to match; so does this.
function setslice!(lines, sc::Scope, i, A, src, idx)
    T, S = valuetype(sc, A), valuetype(sc, src)
    length(idx) == ndims(T) || throw(ArgumentError("$(length(idx)) indices into a $(ndims(T))-dimensional array (statement $i)"))
    spans = [span(sc, T, d, k) for (d, k) in enumerate(idx)]
    spanned = [d for d in eachindex(spans) if !spans[d].scalar]
    Tuple(spans[d].extent for d in spanned) == Tuple(extents(S)) || throw(ArgumentError("assigning a $(describe(S)) into a $(join((spans[d].extent for d in spanned), "×")) slice (statement $i)"))
    source = value(sc, src)
    if mentions(sc, value(sc, A), src)
        # The source is the target's own storage: copy it first.
        t = temp!(sc, nothing, contribution(sc, src))
        emit!(lines, sc, declare(S, t) * ";")
        copy!(lines, sc, source, S, t, S)
        source = t
    end
    start = length(lines) + 1
    setslice!(lines, sc, value(sc, A), T, spans, source, S)
    step!(lines, sc, "$(value(sc, A))[$(join((indexnotation(sc, k) for k in idx), ", "))] = $source"; from=start)
end

# A Julia index as a 0-based C expression.
function zerobased(sc::Scope, k)
    k isa Integer && return string(k - 1)
    text, p = expression(sc, k)
    return (p < ADD ? "($text)" : text) * " - 1"
end

isarray(T) = T <: AbstractArray

# The named variables behind a call's arguments, for temp naming.
parts(sc::Scope, ex::Expr) = unique(reduce(vcat, (contribution(sc, a) for a in ex.args[2:end]); init=String[]))

"""
    temp!(sc, i, parts) -> name

Name the intermediate value `i`, computed from the named variables `parts`.

Temps are `temp1`, `temp2`, … in order of creation within a function, with the names
of the variables used directly in the calculation appended: `temp1_a_b = a + b`.
Literals contribute nothing (`temp2_a = a + 58.3`), a variable appears at most once
(`temp3_a = a * a`), and a temp passes along only its own suffix, never its base
(`temp4_a_b = temp3_a + b`; `temp5_a = temp2 + a`).

A number is skipped if any of the user's own variables is `temp<N>` or `temp<N>_…`,
so there's never confusion about which is which. If the mangled name would be longer
than the scope's limit, the suffix is dropped and the temp is just `temp<N>`.

There is one rule for what any value contributes, temp or not: its name with any
`temp<N>_` chopped off, split into pieces at `_`. So a user's own `temp4_joel_was_here`
contributes `joel_was_here` exactly as one of ours would, and a plain `temp3` contributes
nothing. See `doc/naming.md`.

`i` may be `nothing` for a temp that doesn't stand for any SSA value.
"""
function temp!(sc::Scope, i, parts)
    sc.counter += 1
    while sc.counter in sc.blocked
        sc.counter += 1
    end
    base = "temp$(sc.counter)"
    name = isempty(parts) ? base : base * "_" * join(parts, "_")
    length(name) > sc.limit && (name = base)
    i === nothing || (sc.expr[i] = name)
    return name
end

# The name for an unnamed result. Only one per block; a second falls back to a temp.
function result!(sc::Scope, i)
    name = sc.result
    sc.result = ""
    isempty(name) && return temp!(sc, i, String[])
    sc.expr[i] = name
    return name
end

# Is SSA value `i` used by nothing but return statements?
function onlyreturned(ci, i)
    users = [st for st in ci.code if uses(st, i)]
    return !isempty(users) && all(st -> st isa Core.ReturnNode, users)
end

# The pieces an IR value contributes to a temp's suffix. Literals contribute nothing.
# Anything named contributes its name, minus a leading `temp<N>` (and its `_`), split
# at `_` — the same rule whether the name is one of our temps or the user's own.
function contribution(sc::Scope, x)
    x isa Core.SSAValue || x isa Core.SlotNumber || return String[]
    x isa Core.SSAValue && !(x.id in sc.inlined) && !haskey(sc.expr, x.id) && return String[]   # a constant load
    x isa Core.SSAValue && x.id in sc.inlined && return unique(reduce(vcat, (contribution(sc, a) for a in sc.ci.code[x.id].args[2:end]); init=String[]))
    name = replace(value(sc, x), r"^temp\d+_?" => "", "->" => "_", "." => "_")   # a field read contributes its path: p.x -> p_x
    return filter(!isempty, split(name, "_"))
end

# Can SSA value `i`, which holds the value of `slot` at that point, be written as the
# slot's name at every use? Only if the slot isn't reassigned in between. The textual
# scan is sound for Julia's structured lowering: everything executed between a value's
# definition and a use of it lies between them in the statement list too.
function stable(ci, i, slot)
    for (u, st) in enumerate(ci.code)
        u > i && uses(st, i) || continue
        any(k -> assigns(ci.code[k], slot), i+1:u-1) && return false
    end
    return true
end

# Is `%i = -x`, an array negation, consumed only by a scalar multiply or divide —
# `-x / s`, `-x * s`, `s * -x`? Then the sign moves onto the scalar: `x / (-s)` is
# bit-for-bit `(-x) / s`, since IEEE rounding is symmetric, and a helper call is saved.
function foldable(sc::Scope, i, st::Expr)
    st.head === :call && callee_or_nothing(sc.ci, st.args[1]) === Base.:- && length(st.args) == 2 || return false
    users = [u for (u, s) in enumerate(sc.ci.code) if uses(s, i)]
    length(users) == 1 || return false
    use = sc.ci.code[users[1]]
    use isa Expr && use.head === :(=) && (use = use.args[2])
    use isa Expr && use.head === :call && length(use.args) == 3 || return false
    f = callee_or_nothing(sc.ci, use.args[1])
    scalar(a) = !isarray(valuetype(sc, a))
    f === Base.:/ && return use.args[2] == Core.SSAValue(i) && scalar(use.args[3])
    f === Base.:* && return use.args[2] == Core.SSAValue(i) ? scalar(use.args[3]) : scalar(use.args[2])
    return false
end

isnegated(sc::Scope, a) = a isa Core.SSAValue && a.id in sc.negated

# `-s` for a scalar C expression: a name or number takes the sign directly, anything
# else in parentheses; a leading sign is cancelled rather than doubled.
negate(s::AbstractString) = startswith(s, "-") ? s[2:end] : occursin(r"^[\w.]+(\[[^\]]*\])*$", s) ? "-" * s : "-(" * s * ")"

uses(x, i) = x isa Core.SSAValue   ? x.id == i :
             x isa Expr            ? any(a -> uses(a, i), x.args) :
             x isa Core.ReturnNode ? isdefined(x, :val) && uses(x.val, i) :
             x isa Core.GotoIfNot  ? uses(x.cond, i) : false

assigns(st, slot) = st isa Expr && st.head === :(=) && st.args[1].id == slot

# C precedence levels used by `render`.
const PRIMARY, UNARY, MUL, ADD, SHIFT, REL, EQ, BAND, BXOR, BOR, LAND, LOR = 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4

"""
    render(sc, i, ex) -> (text, precedence)

The C expression for the scalar call `ex`, whose result is SSA value `i`.
"""
function render(sc::Scope, i, ex::Expr)
    ci = sc.ci
    f = callee(ci, ex.args[1])
    args = ex.args[2:end]
    T = widen(ci.ssavaluetypes[i])
    n = length(args)
    # `a + -b` is written `a - b`, and `a - -b` is `a + b`: exact, since a negation
    # is, and what a person writes. A negation is what a right operand that starts
    # with `-` is: anything binding less tightly than `*` has been parenthesised.
    function op(sym, prec)
        s = operand(sc, args[1], prec)
        for a in args[2:end]
            t = operand(sc, a, prec; right=true)
            s *= sym in ("+", "-") && startswith(t, "-") ? (sym == "+" ? " - " : " + ") * t[2:end] : " $sym " * t
        end
        return s, prec
    end
    # `-(-x)` is `x`, exactly.
    unary(sym) = (t = operand(sc, args[1], UNARY); sym == "-" && startswith(t, "-") ? (t[2:end], PRIMARY) : (sym * t, UNARY))
    # A `math.h` function on a `float` is the `f` variant: `sqrtf`, `fabsf`, `powf`.
    fn(name, hdr="math.h") = (push!(sc.headers, hdr); ("$name$(hdr == "math.h" && ctype(T) == "float" ? "f" : "")(" * join((expression(sc, a)[1] for a in args), ", ") * ")", PRIMARY))
    floating = T <: AbstractFloat
    # `zero(x)`, `one(T)`: the literal of the result's type.
    f in (Base.zero, Base.one) && n == 1 && T <: Number && return value(sc, f === Base.zero ? zero(T) : one(T)), PRIMARY

    # A reduction: a helper that returns the scalar.
    if f in (Base.sum, Base.prod, Base.maximum, Base.minimum, Base.any, Base.all, LinearAlgebra.norm, Base.count, Base.argmax, Base.argmin, Base.extrema) &&
       n == 1 && isarray(valuetype(sc, args[1]))
        op = f === LinearAlgebra.norm ? :norm : Symbol(nameof(f))
        op == :norm && push!(sc.headers, "math.h")
        op in (:argmax, :argmin) && ndims(valuetype(sc, args[1])) != 1 && throw(ArgumentError("$op of a $(describe(valuetype(sc, args[1]))) is a CartesianIndex in Julia; not supported (statement $i)"))
        op == :extrema && structdef!(sc.prog, T)   # a (min, max) tuple, returned as a struct
        sc.math[i] = "$op($(value(sc, args[1])))"
        return "$(reducehelper!(sc.helpers, op, valuetype(sc, args[1]), T))($(value(sc, args[1])))", PRIMARY
    end
    # The determinant: a helper that returns the scalar.
    if f === LinearAlgebra.det && n == 1 && isarray(valuetype(sc, args[1]))
        sc.math[i] = "det($(spell(valuetype(sc, args[1]), value(sc, args[1]))))"
        return "$(dethelper!(sc.helpers, valuetype(sc, args[1]), T))($(value(sc, args[1])))", PRIMARY
    end
    # A dot product, or a row times a column: a helper that returns the scalar.
    if (f === LinearAlgebra.dot || f === Base.:*) && n == 2 && all(a -> isarray(valuetype(sc, a)), args) &&
       ndims(valuetype(sc, args[1])) == 1 && ndims(valuetype(sc, args[2])) == 1
        types = (valuetype(sc, args[1]), valuetype(sc, args[2]))
        f === Base.:* && !(isrow(types[1]) && !isrow(types[2])) && throw(ArgumentError("vector * vector is only defined for a row times a column (statement $i)"))
        name = scalarhelper!(sc.helpers, f === LinearAlgebra.dot ? :dot : :mul, types, T)
        sc.math[i] = f === LinearAlgebra.dot ? "$(value(sc, args[1])) ⋅ $(value(sc, args[2]))" : "$(spell(types[1], value(sc, args[1]))) * $(value(sc, args[2]))"
        return "$name($(value(sc, args[1])), $(value(sc, args[2])))", PRIMARY
    end

    # Arithmetic.
    f === Base.:+ && return n == 1 ? expression(sc, args[1]) : op("+", ADD)
    f === Base.:- && return n == 1 ? unary("-") : op("-", ADD)
    f === Base.:* && return op("*", MUL)
    if f === Base.:/
        if all(a -> valuetype(sc, a) <: Integer, args)
            # Julia `/` always produces a float. C promotes an integer operand to the
            # other's floating type on its own, so only integer-by-integer needs help:
            # literals get `.0`, anything else a cast to the result type.
            parts = [a isa Integer ? "$a.0" : "($(ctype(T)))" * operand(sc, a, UNARY) for a in args]
            return join(parts, " / "), MUL
        end
        return op("/", MUL)
    end
    if f === Base.:\ && n == 2
        args = reverse(args)          # a \ b is b / a
        f = Base.:/
        return render(sc, i, Expr(:call, f, args...))
    end
    f === Base.div && return op("/", MUL)
    f === Base.rem && return floating ? fn("fmod") : op("%", MUL)
    if f === Base.mod
        # On floats, Julia's `mod` takes the divisor's sign where C's `fmod` takes the
        # dividend's: a helper (`modhelper!`).
        floating && (push!(sc.headers, "math.h"); return fn(modhelper!(sc.helpers, T), ""))
        a, b = operand(sc, args[1], MUL), operand(sc, args[2], MUL; right=true)
        return "(($a % $b) + $b) % $b", MUL
    end
    if f === Base.literal_pow
        p = ci.ssavaluetypes[args[3].id].val
        p isa Val || throw(ArgumentError("unsupported power (statement $i)"))
        e = typeof(p).parameters[1]
        unit = ctype(T) == "float" ? "1.0f" : floating ? "1.0" : "1"
        e == 0 && return unit, PRIMARY
        e == 1 && return expression(sc, args[2])
        floating || e > 0 || throw(ArgumentError("a negative power of an integer is a DomainError in Julia (statement $i)"))
        x = operand(sc, args[2], MUL)
        # Squares, cubes and the reciprocal are written out; anything else is
        # `powi(x, n)`, by squaring (`powhelper!`).
        e == 2 && return "$x * $x", MUL
        e == 3 && return "$x * $x * $x", MUL
        e == -1 && return "$unit / $x", MUL
        return "$(powhelper!(sc.helpers, T))($(expression(sc, args[2])[1]), $e)", PRIMARY
    end
    if f === Base.:^
        floating || throw(ArgumentError("integer ^ with a non-literal exponent is not supported (statement $i)"))
        return fn("pow")
    end

    # Structs and tuples: field reads, and `==` field by field.
    if f in (Base.getproperty, Core.getfield, Base.getindex) && n == 2 && !isarray(valuetype(sc, args[1])) && (isstruct(valuetype(sc, args[1])) || istuple(valuetype(sc, args[1])))
        return (isindexediterate(sc, args[1]) ? value(sc, args[1]) : fieldaccess(sc, args[1], args[2])), PRIMARY
    end
    if f === Base.:(==) && n == 2 && (isstruct(valuetype(sc, args[1])) || istuple(valuetype(sc, args[1])))
        S = valuetype(sc, args[1])
        a, b = value(sc, args[1]), value(sc, args[2])
        names = fieldcnames(S)
        return join(("$a$(arrow(S))$c == $b$(arrow(S))$c" for c in names), " && "), LAND
    end

    # Comparison and logic.
    f === Base.:<  && return op("<", REL)
    f === Base.:<= && return op("<=", REL)
    f === Base.:>  && return op(">", REL)
    f === Base.:>= && return op(">=", REL)
    f === Base.:(==) && return op("==", EQ)
    f === Base.:!= && return op("!=", EQ)
    f === Base.:(===) && return op("==", EQ)
    f === Base.:! && return unary("!")
    f === Base.not_int && return unary("!")
    f === Base.:& && return op("&", BAND)
    f === Base.:| && return op("|", BOR)
    f === Base.xor && return op("^", BXOR)
    f === Base.:<< && return op("<<", SHIFT)
    f === Base.:>> && return op(">>", SHIFT)
    f === Base.:~ && return unary("~")

    # Math.
    if floating
        f === Base.abs   && return fn("fabs")
        f === Base.max   && return fn("fmax")
        f === Base.min   && return fn("fmin")
        f === Base.round && n == 1 && return fn("rint")            # Julia rounds to even; so does rint
        f === Base.atan  && n == 2 && return fn("atan2")
        for (g, name) in ((Base.sqrt, "sqrt"), (Base.cbrt, "cbrt"), (Base.sin, "sin"), (Base.cos, "cos"), (Base.tan, "tan"),
                          (Base.asin, "asin"), (Base.acos, "acos"), (Base.atan, "atan"), (Base.sinh, "sinh"),
                          (Base.cosh, "cosh"), (Base.tanh, "tanh"), (Base.exp, "exp"), (Base.exp2, "exp2"),
                          (Base.expm1, "expm1"), (Base.log, "log"), (Base.log2, "log2"), (Base.log10, "log10"),
                          (Base.log1p, "log1p"), (Base.floor, "floor"), (Base.ceil, "ceil"), (Base.trunc, "trunc"),
                          (Base.hypot, "hypot"), (Base.copysign, "copysign"))
            f === g && n == length(args) && !(args[1] isa Type) && return fn(name)
        end
    elseif T <: Integer
        f === Base.abs && return T === Int64 ? fn("llabs", "stdlib.h") : T === Int32 ? fn("abs", "stdlib.h") : throw(ArgumentError("abs on $T"))
        if f === Base.max || f === Base.min
            a, b = expression(sc, args[1])[1], expression(sc, args[2])[1]
            return "($a $(f === Base.max ? ">" : "<") $b ? $a : $b)", PRIMARY
        end
        # `round(Int, x)`, `floor(Int, x)`, …: a math function then a cast.
        if f in (Base.round, Base.floor, Base.ceil, Base.trunc) && n == 2
            g = f === Base.round ? "rint" : f === Base.floor ? "floor" : f === Base.ceil ? "ceil" : "trunc"
            push!(sc.headers, "math.h")
            return "($(ctype(T)))$g($(expression(sc, args[2])[1]))", UNARY
        end
    end

    # Classification of a floating value: the same names, from math.h.
    f in (Base.isnan, Base.isinf, Base.isfinite, Base.signbit) && n == 1 && return fn(string(nameof(f)))

    # The limits of a type: the macros C names them by.
    if f in (Base.typemax, Base.typemin, Base.floatmax, Base.floatmin, Base.eps) && (n == 0 || literal(sc, args[1]) isa Type)
        S = n == 0 ? Float64 : literal(sc, args[1])
        S in (Float64, Float32) && f === Base.eps && (push!(sc.headers, "float.h"); return (S === Float64 ? "DBL_EPSILON" : "FLT_EPSILON"), PRIMARY)
        S in (Float64, Float32) && f === Base.floatmax && (push!(sc.headers, "float.h"); return (S === Float64 ? "DBL_MAX" : "FLT_MAX"), PRIMARY)
        S in (Float64, Float32) && f === Base.floatmin && (push!(sc.headers, "float.h"); return (S === Float64 ? "DBL_MIN" : "FLT_MIN"), PRIMARY)
        S in (Float64, Float32) && f === Base.typemax && (push!(sc.headers, "math.h"); return "INFINITY", PRIMARY)
        S in (Float64, Float32) && f === Base.typemin && (push!(sc.headers, "math.h"); return "-INFINITY", UNARY)
        S === Bool && return (f === Base.typemax ? "true" : "false"), PRIMARY
        if S <: Integer && f in (Base.typemax, Base.typemin)
            bits = 8 * sizeof(S)
            S <: Unsigned && return (f === Base.typemax ? "UINT$(bits)_MAX" : "0"), PRIMARY
            return (f === Base.typemax ? "INT$(bits)_MAX" : "INT$(bits)_MIN"), PRIMARY
        end
    end

    # Conversions: a call to a type.
    f isa Type && isstruct(T) && return compound(sc, T, args), PRIMARY
    f isa Type && n == 1 && return "($(ctype(T)))" * operand(sc, args[1], UNARY), UNARY

    # Arrays, as scalars: an element, or a size.
    f === Base.getindex && return index(sc, args[1], args[2:end]), PRIMARY
    f === Base.length && return string(prod(shape(valuetype(sc, args[1])))), PRIMARY
    f === Base.size && n == 2 && return string(shape(valuetype(sc, args[1]))[args[2]]), PRIMARY

    # One of the user's own functions.
    name = usercall!(sc, f, args)
    name === nothing || return "$name($(callargs(sc, args)))", PRIMARY

    throw(ArgumentError("unsupported call: $f (statement $i)"))
end

# An operation along one dimension of an array, into `dest`: a reduction that keeps the
# dimension at extent 1 (`sum(A; dims=1)` of a 2×3 is 1×3), `diff` (the dimension
# shrinks by one), `cumsum` and `cumprod` (the shape stays). The dimension comes from
# the `dims` keyword, or is 1 for a vector; the helper is `sum1_2x3`, `diff2_2x3`,
# `cumsum_4` (`dimhelper!`).
function along!(lines, sc::Scope, i, f, args, kw, dest; declaration::Bool=false)
    op = f === Base.sum ? :sum : f === Base.prod ? :prod : f === Base.maximum ? :maximum : f === Base.minimum ? :minimum :
         f === Base.diff ? :diff : f === Base.cumsum ? :cumsum : f === Base.cumprod ? :cumprod :
         throw(ArgumentError("unsupported operation along a dimension: $f (statement $i)"))
    length(args) == 1 && isarray(valuetype(sc, args[1])) || throw(ArgumentError("$f along a dimension takes one array (statement $i)"))
    T = valuetype(sc, args[1])
    keys(kw) ⊆ (:dims,) || throw(ArgumentError("unsupported keywords for $f: $(join(setdiff(keys(kw), (:dims,)), ", ")) (statement $i)"))
    d = haskey(kw, :dims) ? kw.dims : ndims(T) == 1 ? 1 : throw(ArgumentError("$f of a $(describe(T)) needs dims (statement $i)"))
    d isa Integer && 1 <= d <= ndims(T) || throw(ArgumentError("dims=$d is out of range for a $(describe(T)) (statement $i)"))
    R = widen(sc.ci.ssavaluetypes[i])
    shape(R) === nothing && throw(ArgumentError("the size of $f along dimension $d isn't known (statement $i)"))
    name = dimhelper!(sc.helpers, op, d, T, R)
    declaration && emit!(lines, sc, declare(R, dest) * ";")
    emit!(lines, sc, "$name($(value(sc, args[1])), $dest);")
    step!(lines, sc, "$dest = $op($(value(sc, args[1]))$(ndims(T) == 1 ? "" : "; dims=$d"))")
    sc.shapes[i] = R
end

# `fill!(A, x)`, `A .= 0`, `A .= x`, `A .= B .* 2`: written into the existing array.
function inplace!(lines, sc::Scope, i, st::Expr)
    f = callee(sc.ci, st.args[1])
    dest, D = value(sc, st.args[2]), valuetype(sc, st.args[2])
    isarray(D) || throw(ArgumentError("$f into a $D (statement $i)"))
    x = st.args[3]
    if f === Base.materialize!
        node = sc.ci.code[x.id]                   # broadcasted(g, args...)
        if callee(sc.ci, node.args[2]) === Base.identity && length(node.args) == 3 && !isarray(valuetype(sc, node.args[3]))
            x = node.args[3]                      # `A .= x`: a fill
        else
            return broadcast!(lines, sc, i, x, dest)
        end
    end
    start = length(lines) + 1
    literal(sc, x) == 0 ? zero!(lines, sc, dest, D) : fill!(lines, sc, dest, D, value(sc, eltype(D) <: AbstractFloat && x isa Integer ? eltype(D)(x) : x))
    step!(lines, sc, "$dest .= $(value(sc, x))"; from=start)
end

# `A + λI`, `A - λI`, `λI - A`: the matrix with λ on its diagonal added or subtracted,
# through `addI_3x3(A, λ, out)` and friends (`scalinghelper!`).
function scaling!(lines, sc::Scope, i, op, args, dest; declaration::Bool=false)
    k = findfirst(a -> literal(sc, a) isa LinearAlgebra.UniformScaling, args)
    λ = literal(sc, args[k]).λ
    A = args[3 - k]
    T = valuetype(sc, A)
    isarray(T) && ndims(T) == 2 && allequal(shape(T)) || throw(ArgumentError("I can only be added to a square matrix, not a $(describe(T)) (statement $i)"))
    R = widen(sc.ci.ssavaluetypes[i])
    shape(R) === nothing && (R = T)
    E = eltype(R)
    lam = value(sc, E <: AbstractFloat ? E(λ) : λ)
    mode = op == :add ? :addI : k == 2 ? :subI : :rsubI
    declaration && emit!(lines, sc, declare(R, dest) * ";")
    emit!(lines, sc, "$(scalinghelper!(sc.helpers, mode, T, R))($(value(sc, A)), $lam, $dest);")
    step!(lines, sc, "$dest = " * (mode == :rsubI ? "$(lam)I - $(value(sc, A))" : "$(value(sc, A)) $(op == :add ? "+" : "-") $(lam)I"))
    sc.shapes[i] = R
end

# ---- structs and tuples -------------------------------------------------------------

# The typedef for a struct or tuple type, added to the program once, after the types
# of its fields. Anything that isn't a struct or tuple is ignored.
function structdef!(prog::Program, T::Type)
    (isstruct(T) || istuple(T)) || return
    any(p -> p.first === T, prog.structs) && return
    fields = istuple(T) ? collect(T.parameters) : [fieldtype(T, k) for k in 1:fieldcount(T)]
    for F in fields
        structdef!(prog, F)
    end
    lines = ["    " * declare(F, c) * ";" for (F, c) in zip(fields, fieldcnames(T))]
    push!(prog.structs, T => "typedef struct {\n" * join(lines, "\n") * "\n} $(structname(T));\n")
end

# `p.x`, `c->n`, `t.a`: field `f` (a symbol, or a 1-based position) of the struct or
# tuple value `x`.
function fieldaccess(sc::Scope, x, f)
    S = valuetype(sc, x)
    f = literal(sc, f)
    f isa QuoteNode && (f = f.value)
    return value(sc, x) * arrow(S) * fieldcname(S, f)
end

# Is `x` the result of `indexed_iterate` — a field read in disguise?
isindexediterate(sc::Scope, x) = x isa Core.SSAValue && iscall(sc.ci.code[x.id], Base.indexed_iterate)

# A struct or tuple of type `T` from its field values, as one expression:
# `(Point){x, y}`. Only when no field is an array (C can't initialize an array member
# from another array).
function compound(sc::Scope, T::Type, args)
    isstruct(T) && ismutabletype(T) && throw(ArgumentError("creating a mutable struct ($T) inside transpiled code is not supported; the C caller owns those"))
    structdef!(sc.prog, T)
    any(a -> isarray(valuetype(sc, a)), args) && throw(ArgumentError("a $T holding an array can't be built in an expression"))
    return "($(ctype(T))){$(join((value(sc, a) for a in args), ", "))}"
end

# Build a struct or tuple of type `T` in `dest` (already declared if `declared`): one
# compound literal when every field is a scalar, otherwise field by field with arrays
# copied in.
function compound!(lines, sc::Scope, i, T::Type, args, dest; declared::Bool)
    isstruct(T) && ismutabletype(T) && throw(ArgumentError("creating a mutable struct ($T) inside transpiled code is not supported; the C caller owns those"))
    structdef!(sc.prog, T)
    if !any(a -> isarray(valuetype(sc, a)), args)
        emit!(lines, sc, (declared ? "" : "$(ctype(T)) ") * "$dest = $(compound(sc, T, args));")
        return
    end
    declared || emit!(lines, sc, "$(ctype(T)) $dest;")
    fields = istuple(T) ? collect(T.parameters) : [fieldtype(T, k) for k in 1:fieldcount(T)]
    for (F, c, a) in zip(fields, fieldcnames(T), args)
        isarray(F) ? copy!(lines, sc, value(sc, a), valuetype(sc, a), "$dest.$c", F) :
                     emit!(lines, sc, "$dest.$c = $(value(sc, a));")
    end
end

# Is the tuple made at statement `i` used only by constructors and block
# constructions (or by nothing), so that it never needs to exist in C?
function consumed(ci, i)
    for st in ci.code
        uses(st, i) || continue
        st isa Expr && st.head === :(=) && (st = st.args[2])          # `X = [A B; C D]`
        st isa Expr && st.head === :call || return false
        f = callee_or_nothing(ci, st.args[1])
        (f !== nothing && (isconstruction(f) || f === Base.materialize)) || return false
    end
    return true
end

# ---- step comments ------------------------------------------------------------------

# Record that the C just emitted — everything from line `from` to the last line —
# computes `text`, one step of the current Julia line, in the spelling the helper
# comments use and with the C names: `temp2_A_b_c = temp1_A_b \\ c`. `steps!` turns
# these into comments once the function is built.
function step!(lines, sc::Scope, text; from::Int=length(lines))
    push!(sc.steps, (from, length(lines), text, sc.stmtline[sc.current]))
end

# A value's name in a step comment: `Aᵀ` when it's transposed.
spell(T::Type, name::AbstractString) = istransposed(T) ? name * "ᵀ" : name

# Write the step comments in. On a Julia line that became more than one step, each
# step gets its text — at the end of the line when the step is one statement, on the
# line above when it's a loop or several — so a reader can follow the temps. A line
# that became a single step already has its source comment and needs no more.
function steps!(lines, sc::Scope)
    isempty(sc.steps) && return
    counts = Dict{Int, Int}()
    for (_, _, _, l) in sc.steps
        counts[l] = get(counts, l, 0) + 1
    end
    chosen = [s for s in sc.steps if counts[s[4]] >= 2]
    empty!(sc.steps)
    for (from, at, text, _) in chosen
        if from == at
            lines[at] *= "  // " * text
        else
            indent = lines[from][1:findfirst(!isspace, lines[from])-1]
            push!(sc.inserts, (from, 2, indent * "// " * text))
        end
    end
end

# Whether `x = f(...)` with `x` among the operands can write straight into `x`: yes
# for anything elementwise — `+`, `-`, a scalar multiple or quotient, a broadcast —
# when every operand that is `x` lines up with the result element for element, since
# each output element then depends only on the same elements of the inputs. A product,
# a solve, an inverse, a cross product, a transposed operand or a construction reads
# elements the output has already overwritten, so those go through a temp.
function inplace(sc::Scope, rhs::Expr, R::Type)
    f = callee_or_nothing(sc.ci, rhs.args[1])
    args = rhs.args[2:end]
    if f === Base.materialize
        b = sc.ci.code[args[1].id]
        b isa Expr && b.head === :call && callee_or_nothing(sc.ci, b.args[1]) === Base.broadcasted || return false
        args = b.args[3:end]
    elseif f === Base.:*
        count(a -> isarray(valuetype(sc, a)), args) == 1 || return false
    elseif f === Base.:/
        isarray(valuetype(sc, args[2])) && return false
    elseif !(f in (Base.:+, Base.:-))
        return false
    end
    return all(a -> !isarray(valuetype(sc, a)) || axis(valuetype(sc, a)) == axis(R) && shape(valuetype(sc, a)) == shape(R), args)
end

# ---- calls to other functions -------------------------------------------------------

# A call to one of the user's own functions, at these arguments: its C name, after
# registering the callee's concrete instance to be transpiled if it isn't already. A
# function is the user's if it isn't from Julia itself or the packages the transpiler
# understands. Nothing for anything else.
usercall!(sc::Scope, f, args) = (r = userinstance!(sc, f, args); r === nothing ? nothing : r[3])

# The instance, signature, and C name behind a call to a user function, or nothing.
function userinstance!(sc::Scope, f, args)
    f isa Function || return nothing
    spec = Any[]
    for a in args
        T = valuetype(sc, a)
        T <: Shaped && (push!(spec, eltype(T)); append!(spec, shape(T)); continue)
        push!(spec, juliatype(T))
    end
    nameof(Base.moduleroot(parentmodule(f))) in (:Core, :Base, :LinearAlgebra, :StaticArrays, :Printf) && return nothing
    mi, sig = try
        any(x -> x isa Integer, spec) ? resolve(f, spec) : (m = Base.method_instance(f, Tuple(spec)); m === nothing ? (nothing, nothing) : (m, argtypes(m)))
    catch e
        e isa ArgumentError ? (nothing, nothing) : rethrow()
    end
    mi === nothing && return nothing
    nameof(Base.moduleroot(mi.def.module)) in (:Core, :Base, :LinearAlgebra, :StaticArrays, :Printf) && return nothing
    haskey(sc.prog.calls, mi) && return (mi, sig, sc.prog.calls[mi])
    base = identifier(string(mi.def.name))
    taken = union(sc.prog.names, keys(sc.prog.helpers), reserved)
    name = base in taken ? free(join([base; filter(!isempty, [describe(T, 2, alldouble(sig)) for T in sig])], "_"), taken) : free(base, reserved)
    push!(sc.prog.names, name)
    sc.prog.calls[mi] = name
    push!(sc.prog.pending, (mi, sig, name))
    return (mi, sig, name)
end

# What an instance returns, as the transpiler sees types.
returntype(mi::Core.MethodInstance) = normalize(only(Base.code_typed_by_type(mi.specTypes; optimize=false))[2])

# The Julia type behind a value the transpiler tracks: a row is an `Adjoint` of a
# static vector; an eagerly transposed matrix is the matrix Julia would have made.
function juliatype(T::Type)
    T <: Transposed || return T
    E, S = eltype(T), shape(T)
    ndims(T) == 1 && return LinearAlgebra.Adjoint{E, SVector{S[1], E}}
    return SMatrix{S[2], S[1], E, S[1] * S[2]}
end

# The C arguments of a call: values by name or literal. An eagerly transposed matrix
# would have to be materialized first, since the callee expects Julia's real matrix;
# until that's done, store it in a variable before the call.
function callargs(sc::Scope, args)
    for a in args
        T = valuetype(sc, a)
        istransposed(T) && ndims(T) == 2 && throw(ArgumentError("passing a transposed matrix straight to a function is not supported yet; store it first (B = A')"))
    end
    return join((value(sc, a) for a in args), ", ")
end

# Does the IR value `a` refer to the C variable `x`, looking through the broadcast and
# tuple nodes a construction is built from?
function mentions(sc::Scope, x, a)
    if a isa Core.SSAValue && sc.ci.code[a.id] isa Expr && sc.ci.code[a.id].head === :call
        f = callee_or_nothing(sc.ci, sc.ci.code[a.id].args[1])
        (f === Base.broadcasted || f === Core.tuple) && return any(b -> mentions(sc, x, b), sc.ci.code[a.id].args[2:end])
    end
    v = try value(sc, a) catch; return false end
    return v == x || startswith(v, x * "[") || startswith(v, x * ".")   # the variable, or an element or field of it
end

# ---- ccall ---------------------------------------------------------------------------

# The C for a `ccall`: the symbol called with its arguments, plus a prototype for it
# (or the header it comes from) so the output stands alone. Julia that calls C becomes C
# that calls C.
function foreign!(sc::Scope, st::Expr)
    sym = st.args[1]
    sym isa QuoteNode && (sym = sym.value)
    sym isa Tuple && (sym = sym[1])
    sym isa Symbol || throw(ArgumentError("ccall to a computed function pointer is not supported"))
    name = string(sym)
    R, AT = st.args[2], collect(st.args[3])
    args = foreignargs(sc, st)
    cargs = String[]
    ptypes = String[]
    for (T, a) in zip(AT, args)
        if T <: Ptr
            # A pointer into an array. An immutable static array is passed as Julia
            # passes it, read-only; a mutable one may be written through, which
            # costs our own parameter its `const`.
            V = valuetype(sc, a)
            readonly = isarray(V) && !(V <: Shaped) && !ismutabletype(V)
            readonly || (a isa Core.SlotNumber && push!(sc.mutated, a.id))
            push!(ptypes, (readonly ? "const " : "") * ctype(T.parameters[1]) * " *")
            push!(cargs, isarray(V) ? (ndims(V) == 1 ? value(sc, a) : "&" * value(sc, a) * "[0]"^(ndims(V))) : "&" * value(sc, a))
        elseif T <: Ref
            push!(ptypes, ctype(T.parameters[1]) * " *")
            push!(cargs, "&" * value(sc, a))
        else
            push!(ptypes, ctype(T))
            push!(cargs, value(sc, a))
        end
    end
    header = foreignheader(name)
    if header === nothing
        proto = "$(ctype(R)) $name($(isempty(ptypes) ? "void" : join(ptypes, ", ")));"
        # Two calls that disagree on `const` for a pointer: the prototype takes the
        # weaker promise.
        old = get(sc.prog.foreign, name, proto)
        sc.prog.foreign[name] = old == proto ? proto : replace(proto, "const " => "")
    else
        push!(sc.headers, header)
    end
    return "$name($(join(cargs, ", ")))"
end

# The values a `ccall` passes, with Julia's `cconvert`/`unsafe_convert` wrapping undone.
function foreignargs(sc::Scope, st::Expr)
    n = length(st.args[3])
    function unwrap(a)
        a isa Core.SSAValue || return a
        x = sc.ci.code[a.id]
        x isa Expr && x.head === :call && callee_or_nothing(sc.ci, x.args[1]) in (Base.cconvert, Base.unsafe_convert) && return unwrap(x.args[3])
        return a
    end
    return [unwrap(a) for a in st.args[6:5+n]]
end

# The standard header a `ccall`ed name comes from, if it's one we know; then the output
# includes the header instead of guessing a prototype.
function foreignheader(name::AbstractString)
    (name in mathfunction || name in mathfunction .* "f" || name in mathfunction .* "l") && return "math.h"
    name in ("memset", "memcpy", "memmove", "memcmp", "strlen", "strcmp", "strcpy", "strncpy", "strcat", "strchr", "strstr") && return "string.h"
    name in ("malloc", "calloc", "realloc", "free", "abs", "labs", "llabs", "atoi", "atol", "atof", "strtod", "strtol", "rand", "srand", "exit", "abort", "qsort") && return "stdlib.h"
    name in ("printf", "puts", "putchar", "fflush", "getchar") && return "stdio.h"
    return nothing
end

# `A[i]`, `A[i, j]`: Julia's 1-based indices become 0-based.
function index(sc::Scope, A, idx)
    T = valuetype(sc, A)
    isarray(T) || throw(ArgumentError("indexing into a $T"))
    length(idx) == ndims(T) || throw(ArgumentError("$(length(idx)) indices into a $(ndims(T))-dimensional array"))
    subs = map(idx) do k
        k isa Integer && return string(k - 1)
        text, p = expression(sc, k)
        # The shift to 0-based folds into a literal offset the index already has:
        # `v[i + 1]` is `v[i]`, `v[i - 1]` is `v[i - 2]`.
        if p == ADD && (m = match(r"^(.*) ([+-]) (\d+)$", text)) !== nothing
            off = (m[2] == "+" ? 1 : -1) * parse(Int, m[3]) - 1
            return off == 0 ? m[1] : m[1] * (off > 0 ? " + $off" : " - $(-off)")
        end
        return (p < ADD ? "($text)" : text) * " - 1"
    end
    return value(sc, A) * join("[$s]" for s in subs)
end

# C code for an IR value (a name or literal; use `expression` for inlined calls).
function value(sc::Scope, x)
    if x isa Core.SSAValue
        x.id in sc.inlined && return first(expression(sc, x))
        haskey(sc.expr, x.id) && return sc.expr[x.id]
        sc.ci.code[x.id] isa GlobalRef && return value(sc, sc.ci.code[x.id])
        sc.ci.code[x.id] isa Core.SlotNumber && return sc.names[sc.ci.code[x.id].id]   # a read inside a loop header
        throw(ArgumentError("value of statement $(x.id) is not available in C"))
    end
    x isa Core.SlotNumber && return sc.names[x.id]
    x isa Bool            && return x ? "true" : "false"
    x isa Integer         && return string(x)
    x isa AbstractFloat   && return isinf(x) ? (push!(sc.headers, "math.h"); x > 0 ? "INFINITY" : "-INFINITY") :
                                    isnan(x) ? (push!(sc.headers, "math.h"); "NAN") : x isa Float32 ? replace(string(x), "f" => "e") * "f" : repr(x)
    x isa Irrational      && return x === pi ? constant(sc, "PI") : x === ℯ ? constant(sc, "E") : repr(Float64(x))
    x isa GlobalRef       && return value(sc, getfield(x.mod, x.name))
    throw(ArgumentError("unsupported value: $(repr(x))"))
end

# `M_PI` from `math.h`, which is POSIX rather than ISO C; or, with `portable`, our own
# `LEGIBLEC_PI`, defined at the top of the file.
constant(sc::Scope, name) = sc.prog.portable ? (push!(sc.prog.macros, name); "LEGIBLEC_" * name) : (push!(sc.headers, "math.h"); "M_" * name)

# The type of a value: what inference says, except that an array whose size the IR
# doesn't know is given as the shaped stand-in the transpiler tracks for it.
function valuetype(sc::Scope, x)
    x isa Core.SSAValue   && return get(sc.shapes, x.id, widen(sc.ci.ssavaluetypes[x.id]))
    x isa Core.SlotNumber && return get(sc.slotshapes, x.id, widen(sc.ci.slottypes[x.id]))
    x isa GlobalRef       && return typeof(getfield(x.mod, x.name))
    return typeof(x)
end

# The function object a call refers to. In unoptimized IR the callee is usually an
# SSA value whose statement is a GlobalRef.
function callee(ci, x)
    if x isa Core.SSAValue
        t = ci.ssavaluetypes[x.id]
        t isa Core.Const && (t.val isa Function || t.val isa Type) && return t.val
        return callee(ci, ci.code[x.id])
    end
    x isa GlobalRef     && return getfield(x.mod, x.name)
    x isa Expr && x.head === :call && ci.ssavaluetypes !== nothing && return throw(ArgumentError("unsupported callee: $x"))
    (x isa Function || x isa Type || x isa Colon) && return x
    throw(ArgumentError("unsupported callee: $x"))
end

# Inference wraps known constants as Core.Const and partially-known structs as
# Core.PartialStruct; we only want the type.
widen(t) = normalize(t isa Core.Const ? typeof(t.val) :
                     t isa Core.PartialStruct ? t.typ :
                     t isa Type ? t : throw(ArgumentError("unsupported type lattice element: $t")))
